### ISSUE TITLE
Deprecation notice printed to stdout on PHP 8.1 [Composer 1.10.23]

### ISSUE THREAD

**Issue by dzuelke** [composer/composer#10345]
I know the branch is more or less EOL, but... for people running Composer 1 projects, it's still necessary to install them using Composer 1 if there are plugins involved, so...

```
~ $ PHP_INI_SCAN_DIR= COMPOSER_AUTH= composer --version 2>/dev/null

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///app/.heroku/php/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
Composer version 1.10.23 2021-10-05 09:44:27
```

This obviously breaks programmatic use cases where e.g. the Composer version, config, whatever, is determined by code.

Running without `2>/dev/null` shows that that deprecation notice is different from the others that get printed (which are also ANSI colored); is this a sub-process or something?

```
~ $ PHP_INI_SCAN_DIR= COMPOSER_AUTH= composer --version        
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///app/.heroku/php/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///app/.heroku/php/bin/composer/vendor/symfony/console/Helper/HelperSet.php on line 112
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///app/.heroku/php/bin/composer/src/Composer/Repository/ArrayRepository.php:206
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///app/.heroku/php/bin/composer/src/Composer/Repository/ArrayRepository.php:206
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///app/.heroku/php/bin/composer/src/Composer/Repository/ArrayRepository.php:206
Composer version 1.10.23 2021-10-05 09:44:27
```

**Comment by Seldaek** [comment]
I believe these occur without formatting because they are happening at parsing time and our error handler isn't registered yet.. maybe? Anyway AFAIK it's fixed in 2.x so should be able to backport, although I was hoping I wouldn't have to do that ;)

**Comment by dzuelke** [comment]
So is the `error_reporting` level changed by Composer on startup? I have `error_reporting` set to exclude `E_DEPRECATED`, and it's still happening...

**Comment by Seldaek** [comment]
Yeah there's a gap here between error_reporting set and registering the error handler.. not sure exactly why it'd already load HelperSet nor ArrayRepository before ErrorHandler is registered though

https://github.com/composer/composer/blob/0dbc736eb7e41e3ed327a8e903a1cd886daa383a/bin/composer#L16-L70

Oh but I see, that's from main branch.

1.10 does it later, that explains things: https://github.com/composer/composer/blob/b8e5b1d2d473f42db90094a8d41408afbe5903d4/src/Composer/Console/Application.php#L130

**Comment by Seldaek** [comment]
if you want to send a PR to 1.10 moving error handler registration to match main branch + also backport the changes in ErrorHandler itself to ignore the 8.1 stuff that'd be great.
 https://github.com/composer/composer/blob/e7683e2f60039b5792d506ef62cac2080d29bb33/src/Composer/Util/ErrorHandler.php#L58-L63

Probably should apply the Return type filter to Composer namespace too, not worth fixing this stuff properly in 1.x anymore IMO.

**Comment by dzuelke** [comment]
okay I'll have a look ASAP; hope I can fix this tonight still (it's blocking my ability to roll out 8.1 on Heroku at the moment, so it's easy to justify :))

**Comment by Seldaek** [comment]
Don't expect a release until tomorrow tho, but if you can PR by then it increases the chances it gets resolved tomorrow that's for sure :)

**Comment by dzuelke** [comment]
PR in #10346!
