### ISSUE TITLE
Basic auth infinite loop with incorrect credentials

### ISSUE THREAD

**Issue by joelambert** [composer/composer#11313]
When using basic auth for a private repository and the credentials are incorrect, Composer will keep retrying the download in an infinite loop. The below JSON setup illustrates how to get into this scenario.

Having done some experimentation, this behaviour occurs on a 401 and 403. This appears to have been introduced in `2.3.6` as previous versions work as expected and fail when there is a credentials issue.

My `composer.json`:

```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.packagist.com/my-org"
        },
        {
            "packagist.org": false
        }
    ],
    "config": {
        "allow-plugins": {
            "composer/installers": true
        }
    }
}
```

My `auth.json`:

```json
{
    "http-basic": {
        "repo.packagist.com": {
            "username": "deliberately-wrong",
            "password": "deliberately-wrong"
        }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.delicious-brains/advanced-custom-fields : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK git version 2.37.1
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.2
PHP version: 8.0.21
PHP binary path: /usr/local/Cellar/php@8.0/8.0.21/bin/php
OpenSSL version: OpenSSL 1.1.1p  21 Jun 2022
cURL version: 7.84.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1q
zip: extension present, unzip present, 7-Zip not available
```

When I run this command: 

```
composer require my-org/my-package
```

I get the following output: 

```
Running 2.5.2 (2023-02-04 14:33:22) with PHP 8.0.21 on Darwin / 22.1.0
Reading ./composer.json (/XXX/Desktop/test-repo/composer.json)
Loading config file /XXX/.composer/config.json
Loading config file /XXX/.composer/auth.json
Loading config file ./composer.json (/XXX/Desktop/test-repo/composer.json)
Loading config file /XXX/Desktop/test-repo/auth.json
Reading /XXX/Desktop/test-repo/auth.json
Checked CA file /usr/local/etc/ca-certificates/cert.pem: valid
Executing command (/XXX/Desktop/test-repo): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Executing command (/XXX/Desktop/test-repo): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/XXX/Desktop/test-repo): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/XXX/Desktop/test-repo): hg branch
Executing command (/XXX/Desktop/test-repo): fossil branch list
Executing command (/XXX/Desktop/test-repo): fossil tag list
Executing command (/XXX/Desktop/test-repo): svn info --xml
Reading /XXX/.composer/composer.json
Loading config file /XXX/.composer/config.json
Loading config file /XXX/.composer/auth.json
Loading config file /XXX/.composer/composer.json (/XXX/.composer/composer.json)
Loading config file /XXX/.composer/auth.json
Reading /XXX/.composer/auth.json
Reading /XXX/.composer/vendor/composer/installed.json
Using HTTP basic authentication with username "deliberately-wrong"
Downloading https://repo.packagist.com/my-org/packages.json
[401] https://repo.packagist.com/my-org/packages.json
Warning from repo.packagist.com: 
======================
AUTHENTICATION FAILURE
Invalid username/token
======================

Downloading https://repo.packagist.com/my-org/packages.json
[401] https://repo.packagist.com/my-org/packages.json
Warning from repo.packagist.com: 
======================
AUTHENTICATION FAILURE
Invalid username/token
======================

Downloading https://repo.packagist.com/my-org/packages.json
[401] https://repo.packagist.com/my-org/packages.json
Warning from repo.packagist.com: 
======================
AUTHENTICATION FAILURE
Invalid username/token
======================

Downloading https://repo.packagist.com/my-org/packages.json
[401] https://repo.packagist.com/my-org/packages.json
Warning from repo.packagist.com: 
======================
AUTHENTICATION FAILURE
Invalid username/token
======================

Downloading https://repo.packagist.com/my-org/packages.json
[401] https://repo.packagist.com/my-org/packages.json
Warning from repo.packagist.com: 
======================
AUTHENTICATION FAILURE
Invalid username/token
======================

Downloading https://repo.packagist.com/my-org/packages.json
[401] https://repo.packagist.com/my-org/packages.json
Warning from repo.packagist.com: 
======================
AUTHENTICATION FAILURE
Invalid username/token
======================

Downloading https://repo.packagist.com/my-org/packages.json
[401] https://repo.packagist.com/my-org/packages.json

... REPEATS ...
```

And I expected this to happen:

```
Running 2.3.5 (2022-04-13 16:43:00) with PHP 8.0.21 on Darwin / 22.1.0
Reading ./composer.json (/XXX/Desktop/test-repo/composer.json)
Loading config file /XXX/.composer/config.json
Loading config file /XXX/.composer/auth.json
Loading config file ./composer.json (/XXX/Desktop/test-repo/composer.json)
Loading config file /XXX/Desktop/test-repo/auth.json
Reading /XXX/Desktop/test-repo/auth.json
Checked CA file /usr/local/etc/ca-certificates/cert.pem: valid
Executing command (/XXX/Desktop/test-repo): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Executing command (/XXX/Desktop/test-repo): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/XXX/Desktop/test-repo): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/XXX/Desktop/test-repo): hg branch
Executing command (/XXX/Desktop/test-repo): fossil branch list
Executing command (/XXX/Desktop/test-repo): fossil tag list
Executing command (/XXX/Desktop/test-repo): svn info --xml
Reading /XXX/.composer/composer.json
Loading config file /XXX/.composer/config.json
Loading config file /XXX/.composer/auth.json
Loading config file /XXX/.composer/composer.json (/XXX/.composer/composer.json)
Loading config file /XXX/.composer/auth.json
Reading /XXX/.composer/auth.json
Reading /XXX/.composer/vendor/composer/installed.json
Using HTTP basic authentication with username "deliberately-wrong"
Downloading https://repo.packagist.com/my-org/packages.json
[401] https://repo.packagist.com/my-org/packages.json
Warning from repo.packagist.com: 
======================
AUTHENTICATION FAILURE
Invalid username/token
======================


In AuthHelper.php line 198:
                                                                                        
  [Composer\Downloader\TransportException (401)]                                        
  Invalid credentials for 'https://repo.packagist.com/my-org/packages.json', aborting.  
                                                                                        

Exception trace:
  at phar:///usr/local/bin/composer/src/Composer/Util/AuthHelper.php:198
 Composer\Util\AuthHelper->promptAuthIfNeeded() at phar:///usr/local/bin/composer/src/Composer/Util/Http/CurlDownloader.php:533
 Composer\Util\Http\CurlDownloader->isAuthenticatedRetryNeeded() at phar:///usr/local/bin/composer/src/Composer/Util/Http/CurlDownloader.php:407
 Composer\Util\Http\CurlDownloader->tick() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:378
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:347
 Composer\Util\HttpDownloader->wait() at phar:///usr/local/bin/composer/src/Composer/Util/HttpDownloader.php:109
 Composer\Util\HttpDownloader->get() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:1325
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:1045
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:687
 Composer\Repository\ComposerRepository->hasProviders() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:471
 Composer\Repository\ComposerRepository->loadPackages() at phar:///usr/local/bin/composer/src/Composer/Repository/RepositorySet.php:184
 Composer\Repository\RepositorySet->findPackages() at phar:///usr/local/bin/composer/src/Composer/Package/Version/VersionSelector.php:86
 Composer\Package\Version\VersionSelector->findBestCandidate() at phar:///usr/local/bin/composer/src/Composer/Command/PackageDiscoveryTrait.php:281
 Composer\Command\RequireCommand->findBestVersionAndNameForPackage() at phar:///usr/local/bin/composer/src/Composer/Command/PackageDiscoveryTrait.php:102
 Composer\Command\RequireCommand->determineRequirements() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:204
 Composer\Command\RequireCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:1015
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:334
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:130
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:88
 require() at /usr/local/bin/composer:29

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

**Comment by lgladdy** [comment]
We recently added composer support to Advanced Custom Fields, and noticed this too, so +1 from us on this.

We swapped 401's to 400's to get around this issue in the meantime.

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/11320

**Comment by dlopez-akalam** [comment]
This is still happening with a private packagist authorized by a gitlab token in composer 2.6.0

**Comment by dlopez-akalam** [comment]
After trying several scenarios I was not able to reproduce it anymore
