### ISSUE TITLE
composer install prompts for Basic Auth Username/Password with configured credentials

### ISSUE THREAD

**Issue by CHH** [composer/composer#3830]
I'm installing a private package and I'm authenticating with basic auth. I'm storing the credentials in a global `auth.json` in the COMPOSER_HOME.

When running `php composer.phar install --no-interaction --no-dev --no-ansi --optimize-autoloader` I get the strange error in my deploy script:

```
[RuntimeException]                                                           
  Failed to execute git clone --no-checkout 'REDACTED' 'REDACTED' && cd 'REDACTED' && git remot  
  e add composer 'http://git.redacted.com' && git fetch composer                                                     
  fatal: could not read Username for 'http://git.redacted.com': No such   
  device or address
```

That error message obviously happens because the deploy script hasn't access to `/dev/tty` and thus cannot prompt for the credentials.

The real issue though is, that it's prompting for credentials in the first place, although `store-auths` is set to `false` and `--no-interaction` is passed on the CLI.

The regression must have happened after version `2015-02-27_12-27-56-c7b0628`. That version doesn't exhibit that behavior.

**Comment by CHH** [comment]
Works also with `Composer version 1.0-dev (781d8cb9255505b49266a34e17fd9e9acd56cfd7) 2015-02-14 17:12:21`

**Comment by Seldaek** [comment]
Do you get it with the latest build? I'm wondering if it's also related to the changes in #3813 which also caused another regression (which is fixed).

**Comment by CHH** [comment]
Though, maybe not related, but on another machine I get this error:

```
remote:   Failed to clone git@github.com:omnipay/omnipay.git via git, https, ssh protocols, aborting.  
remote:   - git://github.com/omnipay/omnipay.git                                                       
remote:     fatal: Not a git repository: '.'                                                           
remote:   - https://github.com/omnipay/omnipay.git                                                     
remote:     fatal: Not a git repository: '.'                                                           
remote:   - git@github.com:omnipay/omnipay.git                                                         
remote:     Host key verification failed.                                                              
remote:     fatal: The remote end hung up unexpectedly  
```

(With `Composer version 1.0-dev (b296e654eb3e136ca6fa08fa3bcb1d4782c13f8b) 2015-03-09 11:13:01`, works with `2015-02-14_17-12-21-781d8cb`)

**Comment by CHH** [comment]
@Seldaek I still get the same error with the latest version (`Composer version 1.0-dev (b296e654eb3e136ca6fa08fa3bcb1d4782c13f8b) 2015-03-09 11:13:01`)

**Comment by CHH** [comment]
Works with `2015-03-02_18-20-22-eadc167`. Apparently the regression must have happened after `2015-03-02_18-20-22-eadc167`.

**Comment by frederikbosch** [comment]
https://github.com/composer/composer/blob/master/src/Composer/Util/Git.php

The Git util only accounts for authentication with /dev/try being present. I will extend it and fix the bug this week with a PR.

@Seldaek If you'd like: please cc me in all GitDownloader and GitUtil related issues. I am happy to help with them. Especially when it also concerns authentication.

**Comment by Seldaek** [comment]
@frederikbosch I am not sure what you mean by /dev/try being present or not, but looking forward to a PR, thanks for looking into it.

**Comment by CHH** [comment]
@frederikbosch @Seldaek thanks so much for looking into this!

I'll leave my composer installations downgraded for now :smirk:

**Comment by f7h** [comment]
last working version for me is 8f170b2 (2015-03-04 16:41), 462de7b (2015-03-04 16:44) is not working anymore

**Comment by xepa** [comment]
Same problem here, we are using a password protected https git repo.  
The current way is to remove the user/pass from the git url, this will prompt git clone to write to /dev/tty and read the response from the user, asking for the password.
As far as I know there is no way to capture /dev/tty with pure php, maybe use expect ? but this would introduce another dependancy.

Changing the command slightly: "GIT_ASKPASS=true git clone <etc>" will not prompt the user for a password but will produce a "fatal: Authentication failed .." message on stderr.  

Although it is important not to leak usernames/password via the processlist, I would think it best to add the username and password to the http(s) git url if they exist.

**Comment by frederikbosch** [comment]
As f7h pointed out, #3813 is the pain. More specific, this call was introduced in that pull request.

```php
$process = new Process($command, $cwd, array_replace($_ENV, $_SERVER, array('LANGUAGE' => 'C')), null, static::getTimeout());
```

That line prevents GitUtil::cleanEnv() from being effective. The third parameters is not only adding environment settings (through proc_open inside symfony/process), it seems that it is having a monopoly on the environment settings. Hence, the ```putenv``` commands inside GitUtil are being neglected. A quick fix would be to replace it with the following.

```php
$process = new Process($command, $cwd, array_replace($_ENV, $_SERVER, array('LANGUAGE' => 'C', 'GIT_ASKPASS' => 'echo')), null, static::getTimeout());
```

But that is just a quick fix. There are more ```putenv``` calls inside ```GitUtil::cleanEnv```. Moreover, there is also ```SvnUtil::cleanEnv```.

@Seldaek The question is: how do you want this to be solved? My suggestion is to revert #3813: it is simply introducing more bugs than it is fixing problems. Moreover: that specific language setting could [also be solved in other ways](http://askubuntu.com/questions/320661/change-gits-language-to-english-without-changing-the-locale) - outside composer.

We then have the opportunity to think how to solve these problems correctly. If you'd ask me: remove the static cleanEnv calls and add a method called setEnv inside the process executor.

**Comment by frederikbosch** [comment]
My PR reverts #3813 and tries to fix it differently. Since I am not French, I cannot/will not verify whether the problem of @nicolas-grekas will be solved.

**Comment by frederikbosch** [comment]
@xepa Regarding, leaking usernames/passwords: see PR #3608 .

**Comment by CHH** [comment]
Thanks everybody!

**Comment by Einkoro** [comment]
Is this fixed in f10c71475167a4661225b14560ca0a400d730829? Using --no-interaction isn't prompting anymore but its still failing to use the stored auths or a key for github.

**Comment by frederikbosch** [comment]
@Einkoro You might have another problem then. Consider removing your vendor folder, and try again. See #3608.
