### ISSUE TITLE
Composer not detecting zmq extension

### ISSUE THREAD

**Issue by psychoticmeow** [composer/composer#4353]
I'm trying to use a package that relies on the zmq extension, however when updating I get this message:

```
↪ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for react/zmq 0.3.* -> satisfiable by react/zmq[v0.3.0].
    - react/zmq v0.3.0 requires ext-zmq * -> the requested PHP extension zmq is missing from your system.
```

However it is enabled for the CLI, from the output of `php -i`:

```
ZMQ extension => enabled
ZMQ extension version => 1.1.2
libzmq version => 4.1.2
```

And the output of `php -m`:

```
[PHP Modules]
...
zmq

[Zend Modules]
...
```

It should be working, right?

**Comment by stof** [comment]
@psychoticmeow could it be that you have an alias making ``composer`` run Composer with a different PHP version on your system (maybe with HHVM) ?

Use ``composer show -p`` to see the list of platform packages detected by Composer (if you see ``hhvm`` in it, it means it runs with HHVM btw)

**Comment by psychoticmeow** [comment]
Here is the full output:

```
↪ composer show -p
composer-plugin-api 1.0.0    The Composer Plugin API
ext-bz2             0        The bz2 PHP extension
ext-ctype           0        The ctype PHP extension
ext-curl            0        The curl PHP extension
ext-date            5.6.12   The date PHP extension
ext-dom             20031129 The dom PHP extension
ext-ereg            0        The ereg PHP extension
ext-fileinfo        1.0.5    The fileinfo PHP extension
ext-filter          0.11.0   The filter PHP extension
ext-hash            1.0      The hash PHP extension
ext-intl            1.1.0    The intl PHP extension
ext-json            1.2.1    The json PHP extension
ext-libxml          0        The libxml PHP extension
ext-mbstring        0        The mbstring PHP extension
ext-mhash           0        The mhash PHP extension
ext-mysqlnd         0        The mysqlnd PHP extension
ext-openssl         0        The openssl PHP extension
ext-pcntl           0        The pcntl PHP extension
ext-pcre            0        The pcre PHP extension
ext-PDO             1.0.4dev The PDO PHP extension
ext-Phar            2.0.2    The Phar PHP extension
ext-readline        5.6.12   The readline PHP extension
ext-Reflection      0        The Reflection PHP extension
ext-session         0        The session PHP extension
ext-SimpleXML       0.1      The SimpleXML PHP extension
ext-SPL             0.2      The SPL PHP extension
ext-tokenizer       0.1      The tokenizer PHP extension
ext-xml             0        The xml PHP extension
ext-xmlreader       0.1      The xmlreader PHP extension
ext-xmlwriter       0.1      The xmlwriter PHP extension
ext-zip             1.12.5   The zip PHP extension
ext-zlib            2.0      The zlib PHP extension
lib-curl            7.43.0   The curl PHP library
lib-ICU             55.1     The ICU PHP library
lib-libxml          2.9.2    The libxml PHP library
lib-openssl         1.0.2.4  The openssl PHP library
lib-pcre            8.38-RC1 The pcre PHP library
php                 5.6.12   The PHP interpreter
php-64bit           5.6.12   The PHP interpreter (64bit)
```

**Comment by stof** [comment]
@psychoticmeow can you paste the output of ``php -r 'print_r(get_loaded_extensions());'`` ?

**Comment by psychoticmeow** [comment]
```
↪ php -r 'print_r(get_loaded_extensions());'
Array
(
    [0] => Core
    [1] => date
    [2] => ereg
    [3] => libxml
    [4] => pcre
    [5] => zlib
    [6] => ctype
    [7] => dom
    [8] => fileinfo
    [9] => filter
    [10] => hash
    [11] => json
    [12] => mbstring
    [13] => pcntl
    [14] => SPL
    [15] => PDO
    [16] => readline
    [17] => Reflection
    [18] => session
    [19] => SimpleXML
    [20] => standard
    [21] => tokenizer
    [22] => xml
    [23] => xmlreader
    [24] => xmlwriter
    [25] => mysqlnd
    [26] => bz2
    [27] => curl
    [28] => ftp
    [29] => gd
    [30] => gettext
    [31] => iconv
    [32] => imap
    [33] => inotify
    [34] => intl
    [35] => mcrypt
    [36] => openssl
    [37] => mysql
    [38] => mysqli
    [39] => mongo
    [40] => pdo_mysql
    [41] => pdo_sqlite
    [42] => Phar
    [43] => posix
    [44] => soap
    [45] => sockets
    [46] => sqlite3
    [47] => tidy
    [48] => uv
    [49] => xmlrpc
    [50] => xsl
    [51] => zip
    [52] => zmq
    [53] => mhash
    [54] => xdebug
)
```

**Comment by stof** [comment]
OK, that's weird. zmq appears here.

Is ``php`` running with the same PHP setup than Composer (Composer is running with a 5.6.12 setup)

**Comment by alcohol** [comment]
@psychoticmeow have you resolved this as of yet?

If not, can you share with us what the following commands return?

```
which composer
which php
```

**Comment by madc** [comment]
I've a similar problem involving `ext-gd`. As stated [here](https://github.com/bolt/bolt/issues/4264), composer refuses to find `gd`, even tough it's installed and enabled:

`php --info`:

````
gd

GD Support => enabled
GD headers Version => 2.1.1
GD library Version => 2.1.1
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.6.0
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 8
PNG Support => enabled
libPNG Version => 1.6.18
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled
````

`php -r 'print_r(get_loaded_extensions());'`:

````
Array
(
    [0] => Core
    [1] => date
    [2] => ereg
    [3] => libxml
    [4] => pcre
    [5] => zlib
    [6] => ctype
    [7] => dom
    [8] => fileinfo
    [9] => filter
    [10] => hash
    [11] => json
    [12] => mbstring
    [13] => pcntl
    [14] => SPL
    [15] => PDO
    [16] => readline
    [17] => Reflection
    [18] => session
    [19] => SimpleXML
    [20] => standard
    [21] => tokenizer
    [22] => xml
    [23] => xmlreader
    [24] => xmlwriter
    [25] => mysqlnd
    [26] => curl
    [27] => gd
    [28] => gettext
    [29] => iconv
    [30] => intl
    [31] => mcrypt
    [32] => mysql
    [33] => mysqli
    [34] => openssl
    [35] => pdo_mysql
    [36] => pdo_sqlite
    [37] => Phar
    [38] => sqlite3
    [39] => zip
    [40] => mhash
)
````

`composer show -p`:
````
composer-plugin-api 1.0.0    The Composer Plugin API
ext-bz2             0        The bz2 PHP extension
ext-ctype           0        The ctype PHP extension
ext-curl            0        The curl PHP extension
ext-date            5.6.14   The date PHP extension
ext-dom             20031129 The dom PHP extension
ext-ereg            0        The ereg PHP extension
ext-fileinfo        1.0.5    The fileinfo PHP extension
ext-filter          0.11.0   The filter PHP extension
ext-hash            1.0      The hash PHP extension
ext-intl            1.1.0    The intl PHP extension
ext-json            1.2.1    The json PHP extension
ext-libxml          0        The libxml PHP extension
ext-mbstring        0        The mbstring PHP extension
ext-mhash           0        The mhash PHP extension
ext-mysqlnd         0        The mysqlnd PHP extension
ext-openssl         0        The openssl PHP extension
ext-pcntl           0        The pcntl PHP extension
ext-pcre            0        The pcre PHP extension
ext-PDO             1.0.4dev The PDO PHP extension
ext-Phar            2.0.2    The Phar PHP extension
ext-readline        5.6.14   The readline PHP extension
ext-Reflection      0        The Reflection PHP extension
ext-session         0        The session PHP extension
ext-SimpleXML       0.1      The SimpleXML PHP extension
ext-SPL             0.2      The SPL PHP extension
ext-tokenizer       0.1      The tokenizer PHP extension
ext-xml             0        The xml PHP extension
ext-xmlreader       0.1      The xmlreader PHP extension
ext-xmlwriter       0.1      The xmlwriter PHP extension
ext-zip             1.12.5   The zip PHP extension
ext-zlib            2.0      The zlib PHP extension
lib-curl            7.44.0   The curl PHP library
lib-ICU             55.1     The ICU PHP library
lib-libxml          2.9.2    The libxml PHP library
lib-openssl         1.0.2.4  The openssl PHP library
lib-pcre            8.37     The pcre PHP library
php                 5.6.14   The PHP interpreter
php-64bit           5.6.14   The PHP interpreter (64bit)
````

`which composer`: `/usr/bin/composer`

`which php`: `/usr/bin/php`

**Comment by stof** [comment]
Well, ``ext-gd`` is found for me.

Can you try to run ``/usr/bin/env php -m`` to see whether PHP is found there ? Maybe ``php`` in your shell is resolved as an alias rather than based on the path. composer will not use shall aliases when looking for ``php``

**Comment by madc** [comment]
`/usr/bin/env php -m`:

````
[PHP Modules]
Core
ctype
curl
date
dom
ereg
fileinfo
filter
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
````

**Comment by madc** [comment]
Btw: Its no critical issue to me and i can work around it. So if you're positive its a problem with my system configuration, let me know. Otherwise, I'm happy to provide further information.

**Comment by alcohol** [comment]
Unable to reproduce here too. 

* running Arch
* just installed `php-gd`
* enabled it in `/etc/php/php.ini`
* `composer show -p` lists it

**Comment by madc** [comment]
I updated composer and the issue seems to be solved.

**Comment by alcohol** [comment]
Well, quite a lot has changes since 9f6fdfd7 as you can see [here](/composer/composer/compare/9f6fdfd703f433bd0777fd89fb4684908a6c4f06...HEAD).

Not sure if anything in there actually "fixed" your "problem" though. Would have been interesting to see the results of a `git bisect`.

**Comment by metasystem** [comment]
Hi, have the same problem with Tidy ext, in archlinux too...

**Comment by svycka** [comment]
I am having same problem error log
```bash
$ sudo composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-gd >=2.0 has the wrong version (0) installed.

```
version 0 installed? what?

```bash
$ composer --version
Composer version 1.0-dev (a066171dcc023ad6429881a7692e46f10e080f99) 2015-11-12 13:44:17

$ php -v
PHP 5.6.15-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by svycka** [comment]
Maybe this is because I have dev gd version?
```bash
$ php -r 'var_dump(gd_info());'
Array
(
    [GD Version] => 2.1.1-dev
    [FreeType Support] => 1
    [FreeType Linkage] => with freetype
    [T1Lib Support] => 
    [GIF Read Support] => 1
    [GIF Create Support] => 1
    [JPEG Support] => 1
    [PNG Support] => 1
    [WBMP Support] => 1
    [XPM Support] => 1
    [XBM Support] => 1
    [WebP Support] => 1
    [JIS-mapped Japanese Font Support] => 
)
```

**Comment by Seldaek** [comment]
@svycka it seems it detected the gd version to be 0. Can you run `php -r '$r=new ReflectionExtension("gd");var_dump($r->getVersion());'`? I'm curious to see what it outputs. In any case you can install using `--ignore-platform-reqs` to bypass the gd requirement.

**Comment by svycka** [comment]
@Seldaek, not sure what you want to see but the output:
```php
$ php -r '$r=new ReflectionExtension("gd");var_dump($r->getVersion());'
NULL
```
what it should return?

**Comment by Seldaek** [comment]
It should return an extension version number.. I guess gd is broken and
doesn't respond properly to the reflection calls.

**Comment by svycka** [comment]
@Seldaek, just tested on other VM and production server and few online php testers all return `NULL` all broken?

**Comment by alcohol** [comment]
@Seldaek I just tried it locally and there are actually quite a few extensions that don't return version numbers but `null` instead. Maybe this should be considered simply a 'present' flag from now on?

**Comment by alcohol** [comment]
Although actually looking at the `PlatformRepository` class, if the version cannot be normalized properly (which I am guessing happens in the case of a `null` value), we simply set it to `0`.

So the problem here is that the `composer.json` has specified a specific version, instead of just a wildcard/match-all. So probably they have something like `"require": { "ext-gd": ">2.0" }` which is not going to work since we cannot determine the version of `gd`, we simply can only determine if the host is running with or without the extension.

**Comment by alcohol** [comment]
@svycka if you override the version requirement and simply change it to be `"*"` then it should work just fine :)

**Comment by Seldaek** [comment]
Yeah that should do but it would be good to report it as well to the broken
exts

**Comment by svycka** [comment]
That's what I did but still don't think this is best what composer could do :D Maybe it should show error that it can't get version and info how to get around this or how to fix.

**Comment by alcohol** [comment]
@seldaek I suppose that is true as well. Unfortunately I don't quite know where to find the various repositories/sources to report issues on this. Maybe we could enable the GitHub wiki on this repo and use it to store such information (e.g. stuff that doesn't really belong in the composer documentation).

**Comment by alcohol** [comment]
@svycka I don't quite see how composer could fix this? It already tries to fail as gracefully as possible by simply marking the extension as available (but with version `0`), rather than completely blocking installations by throwing errors. The path of least resistance has my preference here to be honest.

**Comment by svycka** [comment]
I can think of few options:
 1. show error that it can't get version but not 0 version because it is not 0
 2. in case we can't determine version inform user and allow him specify it manually
 3. find other ways of determining extension version

**Comment by Seldaek** [comment]
I think for core exts like gd it can be reported on bugs.php.net, others
have their own tracker or pecl tracker maybe

**Comment by alcohol** [comment]
@svycka too much work for an issue that really is not composer's fault. It should instead be fixed on the appropriate level.

**Comment by svycka** [comment]
@alcohol I agree with this, but if this is problem not just with one or few extensions this is at least worth to consider fixing this or providing more correct error message.

**Comment by alcohol** [comment]
@svycka worth to whom? You're welcome to submit a PR :)

**Comment by svycka** [comment]
people using composer :)
also found this https://bugs.php.net/bug.php?id=40582 looks like this is old issue and very painful one for composer as there is very little chances to get it fixed at extensions side. With 8 or more years not fixed does not give use much hope for fix :D

**Comment by Seldaek** [comment]
It got fixed in a lot of extensions since then so I would say it's worth nagging, or even looking into it and sending a patch, it's probably not extremely difficult but someone has to maintain the number then that's an issue.

**Comment by svycka** [comment]
@Seldaek, just checked how many not fixed on my local box:
```
ereg version: Not avaiable
libxml version: Not avaiable
openssl version: Not avaiable
pcre version: Not avaiable
bcmath version: Not avaiable
bz2 version: Not avaiable
calendar version: Not avaiable
ctype version: Not avaiable
dba version: Not avaiable
ftp version: Not avaiable
gettext version: Not avaiable
iconv version: Not avaiable
mbstring version: Not avaiable
pcntl version: Not avaiable
session version: Not avaiable
posix version: Not avaiable
shmop version: Not avaiable
soap version: Not avaiable
sockets version: Not avaiable
sysvmsg version: Not avaiable
sysvsem version: Not avaiable
sysvshm version: Not avaiable
wddx version: Not avaiable
xml version: Not avaiable
curl version: Not avaiable
gd version: Not avaiable
mcrypt version: Not avaiable
mhash version: Not avaiable
```
and those are pretty common. Maybe I have not latest versions as I use Ubuntu server but at least latest available here without compiling myself :)

**Comment by svycka** [comment]
@Seldaek if you closing this please say how and where this was solved and if not how to workaround this.

**Comment by alcohol** [comment]
@svycka this is not a Composer issue. Please take it upstream :-)

**Comment by svycka** [comment]
@alcohol maybe, but supporting not working feature or relying on not working features this makes no sense :D if this only works with very few extensions then maybe at least should be added warning in the docs or something. Ignoring problems is not the right way to solve things no? :-)

**Comment by Seldaek** [comment]
We can not do anything about it, and we already do work around it by just setting the version to 0 in case an extension returns null, which takes care of the problem as far as I am concerned. If extensions start giving us versions to work with then composer will work with them just fine.
