### ISSUE TITLE
[Composer\Downloader\TransportException]   The "https://packagist.org/packages.json" file could not be downloaded:

### ISSUE THREAD

**Issue by lesm** [composer/composer#4388]
Someone can help me solve this problem
after installing composer and try
composer install
I get this error
[Composer \ Downloader \ TransportException]
   The "https://packagist.org/packages.json" Could not be downloaded file:
https://gyazo.com/fd78cbe9907d46fb5e17ed91d93bb0a7

**Comment by Seldaek** [comment]
Can you post the output of `php -i | grep -i ssl`? It seems like you are stuck using SSLv3 which is disabled on packagist due to security concerns with those outdated protocols.

**Comment by lesm** [comment]
This is the output of  ~~php -i | grep -i ssl~~
https://gyazo.com/20fe9914660342d32c706f8d37c2aa02

What version of openssl should install?

**Comment by Seldaek** [comment]
Well that's weird, your openssl lists the right TLS protocol versions as well, so it should work fine. I'm not sure what's up :/

**Comment by FredoVelcro** [comment]
Same issue when composer update  :  
```text

  [Composer\Downloader\TransportException]
  The "http://packagist.org/p/symfony/stopwatch$0dcb8f42ccb2ac7090f60b2d849260b9d4abbd4284c299639f969bde542f6f2c.json" file could not be downloaded: failed to open stream: HTTP re
  quest failed!
```

**Comment by lesm** [comment]
this was my solution. 
https://gyazo.com/ef952a13bbf04703033b70e66e60047a
#3346

**Comment by sangphobia** [comment]
I  had a similar problem. The issue in my case was the proxy server settings missing. I set it using HTTP_PROXY=<PROXY_IP>:<PROXY_PORT> and HTTPS_PROXY=<PROXY_IP>:<PROXY_PORT>. On doing this, the problem was fixed. You might need to run #composer diagnose via the terminal to confirm if both the HTTP and HTTPS connectivity is ok

**Comment by kyestork** [comment]
Still having issues. Ran `composer diagnose`

    Checking platform settings: OK
    Checking git settings: OK
    Checking http connectivity to packagist: FAIL
    [Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file
    could not be downloaded: failed to open stream: Connection timed out
    Checking https connectivity to packagist: FAIL
    [Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file
    could not be downloaded: failed to open stream: Connection timed out
    Checking github.com rate limit: OK
    Checking disk free space: OK
    Checking composer version:
    
    [Composer\Downloader\TransportException]
    The "https://getcomposer.org/version" file could not be downloaded: failed
    to open stream: Connection timed out
    
    diagnose

**Comment by AlNahari** [comment]
locate cacert.pem

vi /usr/local/lib/php.ini

#add this

openssl.cafile=/usr/local/share/perl5/Mozilla/CA/cacert.pem

#esc 
:wq #enter

curl -sS https://getcomposer.org/installer | php -- —version=1.0.0-alpha10

mv composer.phar /usr/local/bin/composer

alias composer='/usr/local/bin/composer'

composer -V

php /usr/local/bin/composer global self-update

cd .composer/
composer init

**Comment by evertramos** [comment]
Hi there,

I am having the same issue... and I think it started with that when testing PHP 7.

Does it make sense?

**Comment by Seldaek** [comment]
We need more details, make sure you run `composer self-update` and then whatever command fails with `-vvv` to get maximum output.

**Comment by evertramos** [comment]
Here is the error message when running <code>composer self-update -vvv</code>:

>
Downloading https://getcomposer.org/version
[Composer\Downloader\TransportException]
The "https://getcomposer.org/version" file could not be downloaded: failed
to open stream: Connection timed out
Exception trace:
 () at phar:///usr/bin/composer/src/Composer/Util/RemoteFilesystem.php:307
 Composer\Util\RemoteFilesystem->get() at phar:///usr/bin/composer/src/Composer/Util/RemoteFilesystem.php:84
 Composer\Util\RemoteFilesystem->getContents() at phar:///usr/bin/composer/src/Composer/Command/SelfUpdateCommand.php:84
 Composer\Command\SelfUpdateCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:167
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:98
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:43
 require() at /usr/bin/composer:25

>self-update [-r|--rollback] [--clean-backups] [--no-progress] [--] [<version>]

sorry... I could not format it right...

does that help?

I trying the cert.pem from http://curl.haxx.se/ca/cacert.pem and still the same thing.

**Comment by Seldaek** [comment]
`The "https://getcomposer.org/version" file could not be downloaded: failed to open stream: Connection timed out` kinda indicates that the connection timed out i.e. you have no connectivity to getcomposer.org.. Or at least php can't connect to it.. maybe proxy settings are missing or somesuch? But it doesn't sound SSL related.

**Comment by evertramos** [comment]
@Seldaek, I am very sorry to spend your time with things like these... you were right, the firewall was blocking somehow the composer to work. Just fixed the iptables rule. Thank you very much.

**Comment by Seldaek** [comment]
@evertramos no problem it happens. But try to look at the error message in detail :)

Anyway closing this issue as we overhauled the OpenSSL support quite a bit last few days.

**Comment by 547142884** [comment]
It is iptables

**Comment by temuri416** [comment]
In my case disabling ipv6 fixed the problem.

**Comment by gargoyle** [comment]
Not quite sure why it stopped asking, but my solution to the same error for accessing private github repos was to run:-
```
git config --global --add github.accesstoken <super secret token goes here!>
```

**Comment by dlavelle7** [comment]
+1 for @gargoyle, worked for me.

Seems obvious if you want to use the GitHub API to set up an access token :man_facepalming: 

https://help.github.com/articles/creating-an-access-token-for-command-line-use/

**Comment by masoninthesis** [comment]
I'm getting this same issue. It seems to be happening on both my dev machines on my network, so it might be safe to assume it's a networking issue (probably relevant to note that this is the first time I've run composer commands in Hong Kong as opposed to the US).

Here's my output https://gist.github.com/masoninthesis/dd85b216b9c88993d4a06be04c174caf for `php -i | grep -i ssl`:

`Configure Command =>  './configure'  '--prefix=/usr/local/php5' '--with-apxs2=/usr/sbin/apxs' '--with-config-file-scan-dir=/usr/local/php5/php.d' '--with-libxml-dir=shared,/usr' '--with-openssl=/usr/local/php5' '--with-zlib=/usr' '--with-zlib-dir=/usr' '--with-gd' '--with-ldap' '--with-xmlrpc' '--enable-exif' '--enable-soap' '--enable-wddx' '--enable-ftp' '--enable-sockets' '--with-bz2=/usr' '--enable-zip' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-mbstring' '--enable-bcmath' '--enable-calendar' '--with-mhash' '--enable-fpm' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-pcntl' '--enable-dtrace' '--disable-phpdbg' '--enable-opcache' '--with-icu-dir=/usr/local/php5' '--with-xsl=shared,/usr/local/php5' '--with-imap=shared,../imap-2007f' '--with-kerberos=/usr' '--with-imap-ssl=/usr' '--with-gettext=/usr/local/php5' '--with-curl=shared,/usr/local/php5' '--with-png-dir=/usr/local/php5' '--with-jpeg-dir=/usr/local/php5' '--enable-gd-native-ttf' '--with-freetype-dir=/usr/local/php5' '--with-pgsql=shared,/usr/local/php5' '--with-pdo-pgsql=shared,/usr/local/php5' '--with-mcrypt=shared,/usr/local/php5' '--with-tidy=/usr/local/php5' '--with-gmp=shared,/usr/local/php5' '--with-readline=shared,/usr/local/php5' 'CFLAGS=-g -O -mmacosx-version-min=10.10 -I/usr/local/php5/include -arch x86_64 -no-cpp-precomp -DENTROPY_CH_ARCHS='
/usr/local/php5/php.d/40-openssl.ini,
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
SSL => Yes
SSL Version => SecureTransport
SSL Support => enabled
core SSL => supported
extended SSL => supported
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.2h  3 May 2016
OpenSSL Header Version => OpenSSL 1.0.2h  3 May 2016
Openssl default config => /usr/local/php5/ssl/openssl.cnf
openssl.cafile => /usr/local/php5/ssl/certs/cacert.pem => /usr/local/php5/ssl/certs/cacert.pem
openssl.capath => no value => no value
SSL support => enabled
OpenSSL support => enabled`

Output of `composer diagnose`:

`Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK`

Output of `composer self-update -vvv`:

`Reading ./composer.json
Loading config file ./composer.json
Checked CA file /usr/local/etc/openssl/cert.pem: valid
Executing command (/Users/masoninthesis/.composer): git branch --no-color --no-abbrev -v
Executing command (/Users/masoninthesis/.composer): git describe --exact-match --tags
Executing command (/Users/masoninthesis/.composer): git log --pretty="%H" -n1 HEAD
Running 1.3.2 (2017-01-27 18:23:41) with PHP 5.6.25 on Darwin / 16.1.0
Downloading https://getcomposer.org/versions
You are already using composer version 1.3.2 (stable channel).`

I've tried everyone else's solutions except for iptables because I don't know what "fixing the iptables rules" entails (as @evertramos @547142884 suggested).

Any help would be appreciated :)

**Comment by edmundojr** [comment]
It appears to be a problem when using IPv6. Found [this temporary fix](https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues-) that worked for me on macOS:

Get name of the network device you're using:
```
networksetup -listallnetworkservices
```

Disable IPv6 on that device (in my case "Wi-Fi"):
```
networksetup -setv6off Wi-Fi
```

After that just run `composer`, it should work fine!

Visit Composer Troubleshooting page for more info: https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues-

**Comment by Zedonboy** [comment]
hello i get this error...i cant install laravel passport with composer
```
Content-Length mismatch
http://packagist.org could not be fully loaded, package information was loaded f
rom the local cache and may be out of date
```
and file cannot be download error
i have added 
```
 "repositories": [
    {
         "type": "composer", 
         "url": "https://packagist.org"
    },
    { "packagist": false }
],
```
to my composer.json but still nothing works

**Comment by nickfls** [comment]
Sometimes the issue is related to the ipv6 being prioritised over ipv4
[Composer - Operation Timed Out](https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues-)

Change the priority as in:
```sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"```

And voila!

**Comment by JoshuaKeyz** [comment]
@nickfls It worked for me, thank you!

**Comment by ivpfals** [comment]
I've got the error with "HTTP REQUEST FAILED!" solved by exporting the following variable:

export HTTPS_PROXY_REQUEST_FULLURI=false

After that "composer update" works fine, even with a MITM-Proxy used here @ work.

**Comment by cmutwol** [comment]
@sangphobia using HTTP_PROXY=PROXY_IP:PROXY_PORT and HTTPS_PROXY=PROXY_IP:PROXY_PORT works just fine.

**Comment by ZaeemR** [comment]
HTTP_PROXY=PROXY_IP:PROXY_PORT
HTTPS_PROXY=PROXY_IP:PROXY_PORT

These commands did resolve the 'FAIL' issue for the Https but the issue still persists.
`sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf" didn't work for me as well.`

` "config": {
        "preferred-install": "dist",
        "disable-tls": true,
        "secure-http": false
    }`

This config settings also failed to do the required.

Any suggestions?

**Comment by cmutwol** [comment]
@ZaeemR try this
 export HTTPS_PROXY='yourproxy:port'
 export HTTP_PROXY='yourproxy:port'
you can as well export them on ~/.bashrc

**Comment by Hizmarck** [comment]
Check if you are connected to the wifi, my friend happened the same LOL

**Comment by czinco** [comment]
My approach to this consisted of running the `composer clearcache` command. Composer was looking at it's cache and was hitting a 404 trying to get a packagist json file. I hope this helps people get past this.. spent at least 1-2 hours looking into the solution.

**Comment by Tungquantedge** [comment]
C:\xampp\htdocs\form>composer update
The "https://original.packagist.jp/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known.
failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.
https://original.packagist.jp could not be fully loaded, package information was loaded from the local cache and may be out of date
Loading composer repositories with package information
The "https://original.packagist.jp/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known.
failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.
https://original.packagist.jp could not be fully loaded, package information was loaded from the local cache and may be out of date
Updating dependencies (including require-dev)


  [Composer\Downloader\TransportException]
  The "https://original.packagist.jp/p/doctrine/dbal%2417ae46d6beb8d0b5cfd7df33d21dbd21443feeaf54bdc9d841ac03de5ab99c
  1d.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: No such host is known.
  failed to open stream: php_network_getaddresses: getaddrinfo failed: No such host is known.


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by Tungquantedge** [comment]
everybody help me, i don't know why it's have error

**Comment by gargoyle** [comment]
@Tungquantedge You system cannot resolve the name `original.packagist.jp` in order to locate the server. 

As to *WHY* it's trying to use that address, you will have to find out on your own - it looks wrong to me.

**Comment by LuisDariel** [comment]
hi people, i have a similar problem when i try to install composer or use manually yhe composer.phar i get the same error text: **_[Composer\Downloader\TransportException]**                                                                                                                                           
  The "https://packagist.org/packages.json" file could not be downloaded: failed to open stream: Unable to find the socket transport "username" - did you forget to enable it when you  
   configured PHP?_ ."username" it's the user value in HTTP_PROXY varibale configuration. username:password@proxyAddress:proxy_port. some body help me

**Comment by Seldaek** [comment]
@LuisDariel try setting HTTP_PROXY to `tcp://username:password@proxyAddress:proxy_port` or `http://username:password@proxyAddress:proxy_port`.

**Comment by LuisDariel** [comment]
Thank you man, i solve my problem but changing the variable name to HTTPS_PROXY using this protocol y get instal composer with proxy, when i put tcp:// or http:// in front of variable value then the system can't find the configuration.Thanks for your help.

**Comment by LuisDariel** [comment]
I try do that, but the error message change to "Unknow protocol"... and i really need use composer with proxy, becouse i need add to my project a package for to make CRUDs   automatically. If some body know other way for get this package please help me...

**Comment by razorMureithi** [comment]
i cannot figure out the problem.
`composer update --no-interaction --ansi
 Loading composer repositories with package information
 Updating dependencies (including require-dev) 
   [Composer\Downloader\TransportException]
   The "http://packagist.org/p/nesbot/carbon%24eebb9911b7bfc7f57e401fa11b8f063820b8f1c4d9353c9756c4eeea9d4423c3.json" file could not be downloaded: failed to open stream: HTTP request failed!
 
 
 update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
 
 Failed to update packages for  ./composer.json.`

**Comment by LuisDariel** [comment]
Don't worry Razor I solved the problem setting HTTP_PROXY  to tcp://username:password@proxyaddress:proxyport. thanks to Seldaek. but the package for cruds don't work.
i already make its manually. but thank you anyway.

**Comment by pirael** [comment]
this is the error i get when i'm trying to install slim.
The "http://packagist.org/p/provider-2013%2458c8ccbf9ea73c808c11195cc34587b61117fda05caf5e983d9a47a09fd33d61.json" file could not be downloaded: failed to open stream: HTTP request failed!
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date


  [Composer\Downloader\TransportException]
  Content-Length mismatch, received 71277 bytes out of the expected 733150

Any help please on how to do it guys.?

**Comment by fide1** [comment]
The main problem is with proxy setting
After entering the code directory jus enter
1. export http_proxy=proxy address:port 
for example http_proxy=192.123.16.31:8080
2.Repeat the same for https i.e 
export https_proxy=192.123.16.31:8080

**Comment by site-me** [comment]
OK, in my case there was a problem with IPv6, solved it by disabling it in `/etc/sysctl.conf`
by adding in the bottom
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```
and running `sudo sysctl -p` to reload config 

[source](https://medium.com/@lifez/solved-apt-get-update-stuck-connecting-to-security-ubuntu-com-dbe41eeb5a0b)

**Comment by rachanakamlesh** [comment]
If you are Linux(Ubuntu) user then execute the following commands to solve.

php -r "print_r(openssl_get_cert_locations());"

wget http://curl.haxx.se/ca/cacert.pem

sudo mv cacert.pem /usr/lib/ssl/certs/cert.pem // Note: Create the cert.pem file under certs folder if does not exist.

**Comment by mustafaaloko** [comment]
In my case updating `composer` to the latest version `1.7.1` fixed the problem. My previous version was `1.2.3`.

**Comment by JHeisecke** [comment]
@lesm Do you know how I could do this https://gyazo.com/ef952a13bbf04703033b70e66e60047a
#3346 on windows?
[default_cert_file] => c:/usr/local/ssl/cert.pem
I don't know where that is

**Comment by RaminMammadzada** [comment]
I also faced this problem inside the campus. Campus internet network blocked some dns. I changed my network, basically, connect to the internet with my phone via hotspot, it worked.

**Comment by riverlet** [comment]
I solved this by running: 

``` composer self-update ```

**Comment by FarhadHP** [comment]
`composer self-update‍‍`

worked for me.

**Comment by Nabeel02** [comment]
Type composer update in your terminal and after this, download any of the packages you wanted to download.

**Comment by denics** [comment]
I have the same issue with a composer installation of Drupal:
```
  [Composer\Downloader\TransportException]                                                                        
  The "https://packages.drupal.org/7/packages.json" file could not be downloaded (HTTP/1.1 500 Domain Not Found) 
```
This is the error message. I am beyond a proxy on port 80 and the weird issue is that I can download the file without problems using curl or wget, but composer simply fail. The proxy is fine.

**Comment by denics** [comment]
In my case I had to set:

```
HTTP_PROXY=http://my.proxy.org:8080
HTTPS_PROXY=http://my.proxy.org:8080
NO_PROXY=localhost,127.0.0.1,.domain.org
HTTPS_PROXY_REQUEST_FULLURI=false
HTTP_PROXY_REQUEST_FULLURI=true
```

and now everything is working again.

**Comment by Dx3webs** [comment]
weird.. I had to whitelist the IP associated with getcomposer.org in my firewall to allow this through

**Comment by jifromz09** [comment]
![image](https://user-images.githubusercontent.com/43564710/76315369-8085c400-6313-11ea-9968-c8c6fa031b6a.png)


When I run composer diagnose evrythign is fine but when I create a new project it keeps saying "The "https://repo.packagist.org/packages.json" file could not be downloaded: failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

**Comment by pkitatta** [comment]
I think my issue was slow internet.
