### ISSUE TITLE
Problem when installing Composer

### ISSUE THREAD

**Issue by kevinvanryck** [composer/composer#4821]
I'm trying to install Composer, but I get the following problem:

    [user temp]$ curl -s https://getcomposer.org/installer | php -d detect_unicode=Off -d     suhosin.executor.include.whitelist=phar
    Some settings on your machine may cause stability issues with Composer.
    If you encounter issues, try to change the following:

    PHP was compiled with --with-curlwrappers which will cause issues with HTTP authentication and     GitHub.
    Recompile it without this flag if possible

    Downloading...

    Composer successfully installed to: /home/user/temp/composer.phar
    Use it: php composer.phar

    [user temp]$ php composer.phar install
    ??+?[user temp]$ 

And after this, composer isn't installed.

**Comment by Nek-** [comment]
Hello, try to install composer using this command: `curl -sS https://getcomposer.org/installer | php`. I just test it (Ubuntu / PHP 7), it works great.

Then launch it using `php composer.phar`. It should show you the help of composer. If it does not please paste here the error.

Notice that composer needs php with some extensions like json or curl. (errors about extensions missing should be explicit). If you compiled PHP by yourself, be sure everything works as expected.

Notice that this looks more like a problem on your side and here is not a support forum, you should consider post a message on stackoverflow for this kind of problems.

**Comment by kevinvanryck** [comment]
Hi Nek,

If you look at the above log, you will notice that that's what I did. I had to add the -d for PHP, for some settings, otherwise I get the following errors:

    Some settings on your machine make Composer unable to work properly.
    Make sure that you fix the issues listed below and run this script again:

    The detect_unicode setting must be disabled.
    Add the following to the end of your `php.ini`:
        detect_unicode = Off

    The php.ini used by your command-line PHP is: /usr/selector.etc/php.ini
    If you can not modify the ini file, you can also run `php -d option=value` to modify ini values on the fly.         You can use -d multiple times.
    
    The suhosin.executor.include.whitelist setting is incorrect.
    Add the following to the end of your `php.ini` or suhosin.ini (Example path [for Debian]:     /etc/php5/cli/conf.d/suhosin.ini):
        suhosin.executor.include.whitelist = phar 

    The php.ini used by your command-line PHP is: /usr/selector.etc/php.ini
    If you can not modify the ini file, you can also run `php -d option=value` to modify ini values on the fly.     You can use -d multiple times.

So I did as the installer said, add the -d commands.

**Comment by kevinvanryck** [comment]
Fixed, it was a permissions problem :).

**Comment by Akkad86** [comment]
Hi
can you please tell me how you fix it .

still have the same error
