### ISSUE TITLE
Stability with `repositories` and exact version match

### ISSUE THREAD

**Issue by nazar-pc** [composer/composer#4889]
I have Composer integration that automatically generates `composer.json` file, here is an example:
```json
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "modules/Composer",
                "version": "1.0.0-alpha11+cs-1.1.0",
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                },
                "replace": {
                    "nazar-pc/bananahtml": "*",
                    "nazar-pc/upf": "*",
                    "phpmailer/phpmailer": "*"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "modules/Http_server",
                "version": "0.18.2+build-30",
                "require": {
                    "react/http": "0.4.*"
                },
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "modules/WebSockets",
                "version": "0.47.0+build-72",
                "require": {
                    "cboden/ratchet": "0.3.*",
                    "ratchet/pawl": "0.1.*"
                },
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                }
            }
        }
    ],
    "require": {
        "modules/Composer": "1.0.0-alpha11+cs-1.1.0",
        "modules/Http_server": "0.18.2+build-30",
        "modules/WebSockets": "0.47.0+build-72"
    }
}
```

Even though it is explicitly stated that `modules/Composer` is expected to have version `1.0.0-alpha11+cs-1.1.0`, I'm getting an error because of stability:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package modules/composer could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see  for more details.

Read  for further common problems.
```

Expected behavior was that exactly version matching should satisfy stability requirements.

**Comment by alcohol** [comment]
Did you try adding a stability flag to your requirement, e.g. `"modules/Composer": "1.0.0@alpha"` ?

**Comment by nazar-pc** [comment]
No, but I suspect it will work fine. Just wondering why 100% match is additionally checked for some stability requirements, it is obvious that stability check is simply redundant in this case.

**Comment by curry684** [comment]
Not really, as the version itself is essentially just a string. The `@alpha` postfix states that you elect to explicitly ignore the `minimum-stability` which is in place to guard the project as a whole.

**Comment by nazar-pc** [comment]
From my point of view stability requirements are essential if you specify something like `^2.1`, in this case, clearly, you want stable version.

But if there is requirement for `1.0.0-alpha11+cs-1.1.0` and there is indeed version exactly `1.0.0-alpha11+cs-1.1.0` then it is obvious that there is no question about stability here - just accept it if there is no conflicts with anything else (for instance, if someone else requires stable version of this package).

**Comment by curry684** [comment]
In this case it could indeed potentially be magically decided. But internally, for version comparisons, the string `1.0.0-alpha11+cs-1.1.0` is normalized and then padded with zeroes to `1.0.0.0` of stability 'alpha', so it also knows it satisfies `^1.0@alpha`, or `>= 0.8@alpha`, and even `>=0.7@dev` because it knows alpha trumps dev.

On a perfect version match I think Composer could indeed just say 'apparently you want it really bad, let's do it'. I'm not in a position to say why it doesn't - omission or conscious choice. @alcohol know that?

**Comment by alcohol** [comment]
AFAIK, the only time composer implicitly overrides stability modifiers, is when using branch aliases. E.g. if you use `dev-<anybranch>`. The above is simply considered version `1.0.0`, of `alpha` stability (the numeric is only used for sorting precedence). Anything after the + is considered build information and completely irrelevant tot the version.

**Comment by curry684** [comment]
I understand the rationale there, I just can't think of a reason not to also implicitly override it if `$requestedVersion === $fullUnnormalizedVersion`. It would be trivial to add I think, but not spending time on it if it was a conscious decision not to do so in the first place. As the `@alpha` suffix works fine it would just be syntactic sugar, but one I would also expect myself.

**Comment by Seldaek** [comment]
This is fixed by https://github.com/composer/semver/pull/34/files - indeed it should auto-detect the stability but your `+...` version metadata tripped up the detection.

**Comment by nazar-pc** [comment]
Still an issue with `1.0.0-beta1`, example:
```json
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "modules/Composer",
                "version": "1.0.0-beta1+cs-1.0.0",
                "type": "metapackage",
                "require": [],
                "replace": {
                    "nazar-pc/bananahtml": "*",
                    "nazar-pc/upf": "*",
                    "phpmailer/phpmailer": "*"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "modules/Http_server",
                "version": "0.20.1+build-34",
                "type": "metapackage",
                "require": {
                    "react/http": "0.4.*"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "modules/WebSockets",
                "version": "0.47.2+build-74",
                "type": "metapackage",
                "require": {
                    "cboden/ratchet": "0.3.*",
                    "ratchet/pawl": "0.1.*"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "plugins/Composer_assets",
                "version": "1.2.0+build-22",
                "type": "metapackage",
                "require": {
                    "fxp/composer-asset-plugin": "^1.1.2",
                    "oyejorge/less.php": "~1.7",
                    "leafo/scssphp": "^0.6.2"
                },
                "replace": {
                    "bower-asset/iron-flex-layout": "*",
                    "bower-asset/html.sortable": "*",
                    "bower-asset/jquery": "*",
                    "bower-asset/jssha": "*",
                    "bower-asset/polymer": "*",
                    "bower-asset/webcomponentsjs": "*",
                    "npm-asset/jquery": "*",
                    "npm-asset/jssha": "*",
                    "npm-asset/polymer": "*",
                    "npm-asset/webcomponents.js": "*"
                }
            }
        }
    ],
    "require": {
        "modules/Composer": "1.0.0-beta1+cs-1.0.0",
        "modules/Http_server": "0.20.1+build-34",
        "modules/WebSockets": "0.47.2+build-74",
        "plugins/Composer_assets": "1.2.0+build-22"
    }
}
```
Error is exactly the same as before:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package modules/composer could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see  for more details.

Read  for further common problems.
```

**Comment by alcohol** [comment]
@nazar-pc then you are probably not using the latest version of Composer.

**Comment by Seldaek** [comment]
Yes the composer.json you pasted above installs fine for me with latest composer.

**Comment by nazar-pc** [comment]
You are right, it works fine, I've tried it accidentally with older version.
