### ISSUE TITLE
New composer install behind proxy

### ISSUE THREAD

**Issue by ccab** [composer/composer#4919]
Recently I notice the way composer install change and it doesn't work for me now. When I try: 

```
php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
PHP Warning:  readfile(): php_network_getaddresses: getaddrinfo failed: Name or service not known in Command line code on line 1
PHP Warning:  readfile(https://getcomposer.org/installer): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in Command line code on line 1
```

However as a workaround I create the following script:

```
$auth = base64_encode('USER:PASSWORD');

$aContext = array(
    'http' => array(
        'proxy' => 'tcp://PROXY:PORT',
        'request_fulluri' => true,
        'header' => "Proxy-Authorization: Basic $auth",
    ),
);
$cxContext = stream_context_create($aContext);

file_get_contents("http://getcomposer.org/installer", False, $cxContext);
```

So when I run It `php -f test.php > composer-setup.php` I am able to pull It down. 

```
php -r "echo hash('SHA384', file_get_contents('composer-setup.php'));"
781c98992e23d4a5ce559daf0170f8a9b3b91331ddc4a3fa9f7d42b6d981513cdc1411730112495fbf9d59cffbf20fb2
```

But when I try to run the setup:

```
All settings correct for using Composer
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
The download failed repeatedly, aborting.
```

I guess the `file_get_contents` function isn't getting my proxy settings because I can fetch `https://getcomposer.org/composer.phar.sig` and `https://getcomposer.org/composer.phar` with the same script.

**Comment by Seldaek** [comment]
The installer script should take care of using http_proxy/HTTP_PROXY env vars if they are present. You are right about the first line of the install script though, for that if you have a proxy you're better off using curl as `curl https://getcomposer.org/installer > composer-setup.php`

Do you have those env vars defined or not?

**Comment by ccab** [comment]
Yes I have those vars defined both in `http_proxy` and `https_proxy` and I'm able to fetch the installer via `curl`. The same result when I run the installer

**Comment by Seldaek** [comment]
And if you download https://getcomposer.org/composer.phar directly can you then run composer fine or is it also having problems with your proxy settings?

**Comment by ccab** [comment]
Ok I download It 
```
php composer.phar --version
Composer version 1.0-dev (26e7c546b34584220d8c7dd97f98a59b2e39b366) 2016-02-16 09:27:01
```
And this is the diagnose
```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "http://packagist.org/packages.json" file could not be downloaded (HTTP/1.0 407 Proxy Authentication Required)
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
Checking HTTP proxy: FAIL
[Composer\Downloader\TransportException] The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
Checking HTTP proxy support for request_fulluri: FAIL
Unable to assess the situation, maybe packagist.org is down (The 'http://packagist.org/packages.json' URL could not be accessed: HTTP/1.0 400 Bad Request
)
Checking HTTPS proxy support for request_fulluri: FAIL
Unable to assess the situation, maybe github is down (The "https://api.github.com/repos/Seldaek/jsonlint/zipball/1.0.0" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed)
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] The "https://api.github.com/rate_limit" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Failed to enable crypto
failed to open stream: operation failed
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: 
 [Composer\Downloader\TransportException]                    
  The "https://getcomposer.org/version" file could not be do  
  wnloaded: SSL operation failed with code 1. OpenSSL Error   
  messages:                                                   
  error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown  
   protocol                                                   
  Failed to enable crypto                                     
  failed to open stream: operation failed                     
                                                              

diagnose
```
I really don't know if this is a LAMPP problem or if I should use the Ubuntu stack with PHP v5.5.9 but my bet is for a proxy issue

**Comment by curry684** [comment]
> `SSL23_GET_SERVER_HELLO:unknown`

This indicates OpenSSL could not set up a connection supporting **any** version of TLS, as Packagist and GetComposer.org both support 1.0+1.1+1.2. The error shows a common protocol could not be negotiated.

I suspect the proxy you're using is really, REALLY outdated.

**Comment by ccab** [comment]
I don't think so, this is an output of `curl` using the same proxy:
```
curl -v https://getcomposer.org/version
*   Trying PROXY_IP...
* Connected to PROXY_IP (PROXY_IP) port 3128 (#0)
* Establish HTTP proxy tunnel to getcomposer.org:443
* Proxy auth using Basic with user 'PROXY_USER'
> CONNECT getcomposer.org:443 HTTP/1.1
> Host: getcomposer.org:443
> Proxy-Authorization: Basic YWlqbTEtZ2FkMTpHZmMrMTVhag==
> User-Agent: curl/7.45.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied OK to CONNECT request
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/lampp/share/curl/curl-ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Unknown (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: C=CH; ST=Z�rich; L=Z�rich; O=Nelmio AG; CN=getcomposer.org
* 	 start date: Jun 30 00:00:00 2014 GMT
* 	 expire date: Aug  1 12:00:00 2017 GMT
* 	 subjectAltName: getcomposer.org matched
* 	 issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
* 	 SSL certificate verify ok.
> GET /version HTTP/1.1
> Host: getcomposer.org
> User-Agent: curl/7.45.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 16 Feb 2016 13:28:41 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 41
< Last-Modified: Tue, 16 Feb 2016 13:25:07 GMT
< Connection: keep-alive
< ETag: "56c32333-29"
< Accept-Ranges: bytes
< 
aea6045668942f579da7d90fc82008928c06cfd2
* Connection #0 to host PROXY_IP left intact
```

**Comment by Seldaek** [comment]
Then maybe your php openssl is too old?! But it seemed to work in that 
file you wrote yourself though..

**Comment by stof** [comment]
Then check the openssl version used by your PHP setup. It may be the one being totally outdated

**Comment by ccab** [comment]
```
php composer.phar show -p | grep openssl
ext-openssl         0        The openssl PHP extension
lib-openssl         1.0.1.17 OpenSSL 1.0.1q 3 Dec 2015

```

**Comment by ccab** [comment]
Is there any other command or way around to show the openssl info ??

**Comment by curry684** [comment]
`php -r "phpinfo();"` will show an entire section about it, but it's similar to what `show -p` shows.

**Comment by ccab** [comment]
```
php -r "phpinfo();" | grep ssl
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, sslv2, tls, tlsv1.0, tlsv1.1, tlsv1.2
openssl
Openssl default config => /opt/lampp/share/openssl/openssl.cnf
openssl.cafile => /opt/lampp/share/curl/curl-ca-bundle.crt => /opt/lampp/share/curl/curl-ca-bundle.crt
openssl.capath => no value => no value

```

**Comment by Seldaek** [comment]
BTW `php -r 'phpinfo();'` == `php -i` ;)

Anyway.. if you say that your script in original issue:

**Comment by Seldaek** [comment]
BTW `php -r 'phpinfo();'` == `php -i` ;)

Anyway.. if you say that your script works in original issue, php is maybe not at fault, but I noticed that you used `file_get_contents("http://getcomposer.org/installer", False, $cxContext);` with an http and not https URL, so that doesn't prove a whole lot unfortunately regarding TLS.

One difference I see is that it seems curl connects to your proxy on port 80 first initiating an HTTP tunnel. Do you provide an https_proxy env variable as well? Because if you do then composer takes that for https urls instead of using http_proxy.

**Comment by ccab** [comment]
As additional info I download the `.crt` file via `wget curl.haxx.se/ca/ca-bundle.crt` and I put it into `/opt/lampp/share/curl/curl-ca-bundle.crt`. 

This is my new script and it works ok:
```
$auth = base64_encode('USER:PASSWORD');

$aContext = array(
    'http' => array(
        'proxy' => 'tcp://IP_ADDRESS:PORT',
        'request_fulluri' => true,
        'header' => "Proxy-Authorization: Basic $auth",
    ),
);
$cxContext = stream_context_create($aContext);

readfile("https://getcomposer.org/installer", false, $cxContext);
```
I got both `http_proxy` and `https_proxy` defined

**Comment by Seldaek** [comment]
Would you mind sharing the values you have for http_proxy and 
https_proxy? You can change the ip/domain/user/pass of course but try to 
keep them as real looking as you can.

**Comment by ccab** [comment]
Ok this is my settings:
```
env | grep proxy
http_proxy=http://USER:PASSW@192.168.1.11:3128
https_proxy=https://USER:PASSW@192.168.1.11:3128

```

**Comment by Seldaek** [comment]
OK then in that case can you try with:

```
$auth = base64_encode('USER:PASSWORD');

$aContext = array(
    'http' => array(
        'proxy' => 'ssl://192.168.1.11:3128',
        'request_fulluri' => true,
        'header' => "Proxy-Authorization: Basic $auth",
    ),
);
$cxContext = stream_context_create($aContext);

readfile("https://getcomposer.org/installer", false, $cxContext);
```

Basically I just changed tcp:// to ssl://, as that is what composer uses for https:// proxies. I guess maybe your proxy does not support ssl by itself, and therefore you shouldn't specify it in https_proxy? Can you try if you unset that variable if everything works?

**Comment by ccab** [comment]
Ok I change my script and it works fine, It download the installer, now the `env` vars look like this:
```
# env | grep proxy
http_proxy=http://USER:PASSW@192.168.1.11:3128
https_proxy=

```
And this is the end result:
```
# php composer-setup.php 
All settings correct for using Composer
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
Downloading...
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
Download failed: file_get_contents(https://getcomposer.org/composer.phar.sig): failed to open stream: Cannot connect to HTTPS server through proxy
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
The download failed repeatedly, aborting.

```

**Comment by Seldaek** [comment]
So still no luck? I'm lost here sorry..

**Comment by staabm** [comment]
In https://github.com/composer/composer/issues/2021 a similar issue was fixed by updating openssl

**Comment by staabm** [comment]
some others in http://stackoverflow.com/questions/17307600/php-composer-behind-http-proxy suggest to set a env var `export HTTPS_PROXY_REQUEST_FULLURI=false`

**Comment by ccab** [comment]
Ok now I set `http_proxy`, `HTTP_PROXY`, `HTTP_PROXY_REQUEST_FULLURI` none https and I can download the installer via the script (still can't by the `php -r` command) and running `php composer-setup.php` as well, but this is my diagnose: 
```
php composer.phar diag
Checking composer.json: FAIL
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.monolog/monolog : unbound version constraints (>=1.0.0) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: FAIL
[Composer\Downloader\TransportException] The 'http://packagist.org/packages.json' URL could not be accessed: HTTP/1.0 400 Bad Request

Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: FAIL
Unable to assess the situation, maybe packagist.org is down (The 'http://packagist.org/packages.json' URL could not be accessed: HTTP/1.0 400 Bad Request
)
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```
I also got a `composer.json` file:
```
{
    "require": {
        "monolog/monolog": ">=1.0.0"
    }
}
```
So, we are getting closer:
```
php composer.phar -vvv install
Reading ./composer.json
Loading config file ./composer.json
Checking CA file /opt/lampp/share/curl/curl-ca-bundle.crt
Executing command (/root): git describe --exact-match --tags
Executing command (/root): git branch --no-color --no-abbrev -v
Executing command (/root): hg branch
Executing command (/root): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /root/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /root/.cache/composer/repo/https---packagist.org/packages.json into cache
Installing dependencies (including require-dev)
Downloading http://packagist.org/p/provider-2013%24907f12bc7ed756034fb97405ced3ebfe769ac49a0786554246a14a1b23ffba8e.json
Downloading http://packagist.org/p/provider-2013%24907f12bc7ed756034fb97405ced3ebfe769ac49a0786554246a14a1b23ffba8e.json
Downloading http://packagist.org/p/provider-2013%24907f12bc7ed756034fb97405ced3ebfe769ac49a0786554246a14a1b23ffba8e.json

                                                                                                                                       
  [Composer\Downloader\TransportException]                                                                                             
  The 'http://packagist.org/p/provider-2013%24907f12bc7ed756034fb97405ced3ebfe769ac49a0786554246a14a1b23ffba8e.json' URL could not be  
   accessed: HTTP/1.0 400 Bad Request                                                                                                  
                                                                                                                                       

Exception trace:
 () at phar:///root/composer.phar/src/Composer/Util/RemoteFilesystem.php:480
 Composer\Util\RemoteFilesystem->callbackGet() at n/a:n/a
 file_get_contents() at phar:///root/composer.phar/src/Composer/Util/RemoteFilesystem.php:267
 Composer\Util\RemoteFilesystem->get() at phar:///root/composer.phar/src/Composer/Util/RemoteFilesystem.php:98
 Composer\Util\RemoteFilesystem->getContents() at phar:///root/composer.phar/src/Composer/Repository/ComposerRepository.php:627
 Composer\Repository\ComposerRepository->fetchFile() at phar:///root/composer.phar/src/Composer/Repository/ComposerRepository.php:540
 Composer\Repository\ComposerRepository->loadProviderListings() at phar:///root/composer.phar/src/Composer/Repository/ComposerRepository.php:282
 Composer\Repository\ComposerRepository->whatProvides() at phar:///root/composer.phar/src/Composer/DependencyResolver/Pool.php:199
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///root/composer.phar/src/Composer/DependencyResolver/Pool.php:188
 Composer\DependencyResolver\Pool->whatProvides() at phar:///root/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:168
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar:///root/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:322
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar:///root/composer.phar/src/Composer/DependencyResolver/Solver.php:208
 Composer\DependencyResolver\Solver->solve() at phar:///root/composer.phar/src/Composer/Installer.php:508
 Composer\Installer->doInstall() at phar:///root/composer.phar/src/Composer/Installer.php:217
 Composer\Installer->run() at phar:///root/composer.phar/src/Composer/Command/InstallCommand.php:134
 Composer\Command\InstallCommand->execute() at phar:///root/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///root/composer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///root/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///root/composer.phar/src/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at phar:///root/composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///root/composer.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar:///root/composer.phar/bin/composer:43
 require() at /root/composer.phar:25

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

```

**Comment by ccab** [comment]
Now just setting with these
```
HTTP_PROXY_REQUEST_FULLURI=false
HTTP_PROXY=http://USER:PASSW@192.168.1.11:3128
```
I could even update my installer
```
php composer.phar self-update
Updating to version 93501a5e3f8433e982da3518e13896ee4c0e816b.
    Downloading: 100%         
Use composer self-update --rollback to return to version d6d0435c5437111e42a123b06e4071e26ba7cb6e
```
But I can't install at all. @Seldaek there is a way to set the `file_get_contents` used by the installer something like in my script or it's already done ??

**Comment by Seldaek** [comment]
The installer and composer both use more or less the same code to handle HTTP_PROXY and related env vars. I don't know why the hell one would work and the other not to be honest.

One thing that seems to be missing is HTTPS_PROXY support in the installer, but you don't seem to use that anyway?

**Comment by Seldaek** [comment]
BTW, the first line of the installer instructions i.e. `php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php` will not work with a proxy that's normal IMO and not much we can do there. But if you download it with `curl https://getcomposer.org/installer > composer-setup.php` then the rest of instructions should work.

**Comment by cs278** [comment]
> Ok this are my settings:
> 
> env | grep proxy
> http_proxy=http://USER:PASSW@192.168.1.11:3128
> https_proxy=https://USER:PASSW@192.168.1.11:3128

Seems a bit off proxy offering http and https on the same port. Have you tried?

```
http_proxy=http://USER:PASSW@192.168.1.11:3128
https_proxy=http://USER:PASSW@192.168.1.11:3128
```

**Comment by ccab** [comment]
Ok I got it working now, but I'm not quite sure about my solution. I set `HTTP_PROXY` env var just this one and now its running just fine, I don't know if it's an issue with Ubuntu, php version, composer or what else. I'll keep digging 
@Seldaek I don't know if its a normal behavior, through `HTTP_PROXY` ? Because I'm confused 
>Do you provide an https_proxy env variable as well? Because if you do then composer takes that for https urls instead of using http_proxy.
 
Now I'm more confident
>BTW, the first line of the installer instructions i.e. php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php will not work with a proxy that's normal
 
What do you think if we make an annotation in the composer website about it ??

**Comment by cs278** [comment]
Hmm Composer seems (I haven't tested and my eyes are barely open) to use `http_proxy` for https URLs, which is not what curl does. Look at the environment section in the curl man page: https://curl.haxx.se/docs/manpage.html @Seldaek?

**Comment by curry684** [comment]
It shouldn't according to https://github.com/composer/composer/blob/fbab2bfa173e1bf3667051b99bf544cccad1ad9d/src/Composer/Util/StreamContextFactory.php#L43

**Comment by staabm** [comment]
> It first downloads the packages.json through https, then switches for some vague reason to http for the includes.

AFAIR it uses https for packages.json to make sure noone in the middle can intercept the process and let you download malicous packages. the packages itself are downloaded via http for perf reasons.

**Comment by curry684** [comment]
Hmm that's right, that's really a micro-optimization. The consequence however seems the same - `400 Bad Request` nearly always boils down to speaking SSL to an unencrypted HTTP server in my experience.

**Comment by Seldaek** [comment]
It's not really a micro optimization, the https connection setup time is quite long and since php streams can't do keepalive we end up opening many connections.

**Comment by cs278** [comment]
> It shouldn't according to https://github.com/composer/composer/blob/fbab2bfa173e1bf3667051b99bf544cccad1ad9d/src/Composer/Util/StreamContextFactory.php#L43

If you pass in a `https://` URL it will use the value from `http_proxy` according to that line.

Good point about the protocol switching, if you get a redirect to a URL that uses a different proxy or should bypass a proxy it will still attempt to use the proxy.

**Comment by curry684** [comment]
Yes it does but line 49 below overwrites it with the `HTTPS_PROXY` value if set and https url.

The underlying issue seems to be indeed that protocol switches do not use the right URL. Bringing us to that the optimization, micro or not, is invalid as http://packagist.org/p/provider-2013%24907f12bc7ed756034fb97405ced3ebfe769ac49a0786554246a14a1b23ffba8e.json instantly redirects with a 307 to the https version right now.

So yes, it would appear that the issue is with Composer still trying those URLs as plain http, not setting the `HTTPS_PROXY` for that, and the internal redirect being handled at curl level causing the `http_proxy` to be used for https, explaining the 400 error.

**Comment by Seldaek** [comment]
There is no redirect to https for static files. This one redirects because it's a 404 so it gets handled by symfony which then redirects to force https. If you try a valid url it'll go through over http just fine.

**Comment by curry684** [comment]
Errr true, but why is that URL invalid as I copy/pasted it from the error logs?
```
  [Composer\Downloader\TransportException]                                                                                             
  The 'http://packagist.org/p/provider-2013%24907f12bc7ed756034fb97405ced3ebfe769ac49a0786554246a14a1b23ffba8e.json' URL could not be  
   accessed: HTTP/1.0 400 Bad Request  
```

**Comment by Seldaek** [comment]
Because those URLs are based on the file content hash so they change often and old files get cleaned up.

**Comment by curry684** [comment]
That fast? So it could very well be that the proxy is caching the `packages.json` a day as it's a static file, serving the client a somewhat outdated version, referencing a sub-include that no longer exists, causing the HTTPS redirect, thus exposing the HTTPS_PROXY mismatch issue on curl internal redirects?

**Comment by Seldaek** [comment]
If the proxy is completely borked and caching what it shouldn't cache, sure it's possible. We clean up files hourly IIRC.

**Comment by curry684** [comment]
The response headers on `packages.json` are:
```
Accept-Ranges:bytes
Connection:keep-alive
Content-Length:1181
Content-Type:application/json
Date:Fri, 19 Feb 2016 15:00:38 GMT
ETag:"56c72e01-49d"
Last-Modified:Fri, 19 Feb 2016 15:00:17 GMT
Server:nginx
```
Just an ETag, no `Cache-control` or `Expires`. I wouldn't at all be surprised if this is what's happening if the file starts causing this after an hour. As there is no `must-revalidate` rule or anything these headers tell the proxy it's essentially fine to cache this file for an arbitrary time.

I would at the very least configure nginx to add:

    cache-control: private, max-age=0, no-cache,

**Comment by Seldaek** [comment]
Fair enough, I added no-cache headers on that file now.

**Comment by cs278** [comment]
> Yes it does but line 49 below overwrites it with the HTTPS_PROXY value if set and requesting an https url.

And if `HTTP_PROXY` is unset? Composer uses the value of `http_proxy` to proxy https requests, this is not how curl works and I guess others.

```
chris@kinslayer:~ $ http_proxy=http://127.0.0.1:3000 curl -sv http://example.com/ > /dev/null
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 3000 failed: Connection refused
* Failed to connect to 127.0.0.1 port 3000: Connection refused
* Closing connection 0
chris@kinslayer:~ $ http_proxy=http://127.0.0.1:3000 curl -sv https://example.com/ > /dev/null
* Hostname was NOT found in DNS cache
*   Trying 93.184.216.34...
* Connected to example.com (93.184.216.34) port 443 (#0)
snip
* Connection #0 to host example.com left intact
```

**Comment by dzanwari** [comment]
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getadd
  resses: getaddrinfo failed: Name or service not known
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not k
  nown

**Comment by stof** [comment]
well, looks like your PHP setup is not able to resolve the DNS

**Comment by Seldaek** [comment]
Auto-closing this as it's marked as support request and has not received any update in a long time.

**Comment by CesarBallardini** [comment]
FIX: 

unset no_proxy and NO_PROXY environment variables
