### ISSUE TITLE
json do not match its signature issue 

### ISSUE THREAD

**Issue by omerbsh** [composer/composer#5196]
With the following composer.json:
(none)

``` json
{
    ...
}
```

When I run this command:

```
composer command -vvv (please include -vvv!)
```

I get this output:

```
  [Composer\Repository\RepositorySecurityException]                                                                                                   
  The contents of http://packagist.org/p/provider-2014%24778fe81238370a6a10514fa2191d8c49e3b0df47ad7c25361bda5e7c0f48797c.json do not match its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.                    

```

And I expected this to happen:
install cakephp package.

**Comment by curry684** [comment]
Please edit the template a bit more to supply an actual problem case.

**Comment by omerbsh** [comment]
When I try to install by the command "php composer.phar create-project --prefer-dist laravel/laravel public" i get the attached error message.

I wonder if the problem is with the CRT on my computer or on the servers?

**Comment by alcohol** [comment]
Are you behind a proxy or any kind of firewall software?

If the error consistently occurs, one of the above is probably mangling your connections.

**Comment by omerbsh** [comment]
Hey,

no use of proxy, i changed machine and i still get the same error.

[Composer\Repository\RepositorySecurityException]                                                                                                   
  The contents of http://packagist.org/p/provider-2014%24778fe81238370a6a10514fa2191d8c49e3b0df47ad7c25361bda5e7c0f48797c.json do not match its sign  
  ature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.

**Comment by alcohol** [comment]
Different machine, but same network?

**Comment by omerbsh** [comment]
Yes, its virtual machines on my computer (Debian).

**Comment by alcohol** [comment]
Sorry, not really sure what could be wrong here. But it is definitely a networking issue, nothing we can solve for you.

**Comment by Kendysond** [comment]
add this to your composer
```
"repositories": {
    "packagist": { "url": "https://packagist.org", "type": "composer" }
 }
```

**Comment by smilezv** [comment]
"repositories": {
    "packagist": { "url": "https://packagist.org", "type": "composer" }
 }
This code above fix the signature issue. 

[Composer\Repository\RepositorySecurityException]
The contents of http://packagist.org/p/provider-2014%24778fe81238370a6a10514fa2191d8c49e3b0df47ad7c25361bda5e7c0f48797c.json do not match its sign
ature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.

**Comment by phil-davis** [comment]
I have had this problem in the morning yesterday and today, and on various days in the past. In my timezone that is early AM hours UTC. Then the problem goes away in the afternoon evening. So I am suspicious that there are daily updates to the package list, and the signature file also gets updated, but somewhere "in the big bad internet" they are cached differently. And so for some hours I receive a new file+old signature or old file+new signature. It is rather annoying!

```
[Composer\Repository\RepositorySecurityException]                                                                          
The contents of http://packagist.org/p/provider-2013%2453bd1fb568f984a10d7aa50e4d388dce7787e9d744d748e09a2f3ceadaae5cd1.json do not match its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.     
```
I will try regularly now to see if there is a real time pattern to this.

**Comment by curry684** [comment]
> This should indicate a man-in-the-middle attack.

That should actually say "could" hehe.

**Comment by furious-snail** [comment]
I get a similar error when running composer require symfony/security-checker:
`[Composer\Repository\RepositorySecurityException]                                                                                                         
  The contents of https://packagist.org/p/providerlatest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json do not match its signature. This could indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.`
Adding
`"repositories": {
        "packagist": { "url": "https://packagist.org", "type": "composer" }
    }`
doesn't help. Any suggestions are welcome.
Thank you.

**Comment by rickselby** [comment]
@furious-snail Looks like packagist.org is down right now.

**Comment by laurentvd** [comment]
It seems to be working again!

**Comment by furious-snail** [comment]
I tried a couple of times. When accessing the https://packagist.org it is working.
Thank you.

**Comment by munzeedaniel** [comment]
Same problem here. Adding 
`"repositories": { "packagist": { "url": "https://packagist.org", "type": "composer" } }`
does not help.

**Comment by hoonzis** [comment]
Same problem here, adding packagist url explicitly didn't work

**Comment by necipallef** [comment]
I can access the website, but I still get the following when I `composer update`:

`The contents of https://packagist.org/p/provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json do not match its signature. This could indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake`

**Comment by jscontrust** [comment]
Same here

**Comment by yuriyse** [comment]
Similarly..

**Comment by svenfinke** [comment]
Yeah, seems like packagist is down, or at least the service does not work as expected.

**Comment by jibay** [comment]
Same here :/

**Comment by mragvlik** [comment]
Just wait

**Comment by Okipa** [comment]
I think this is related to the recent service interruption of packagist.  
<img width="588" alt="capture d ecran 2018-01-16 a 15 28 13" src="https://user-images.githubusercontent.com/5328934/34993875-0166a67c-fad2-11e7-96c5-f8994472609d.png">
More infos on : https://twitter.com/packagist

**Comment by milosilic** [comment]
same here

**Comment by Keirul** [comment]
Thanks for the update @Okipa, FYI DNS related issue at Packagist.

**Comment by arthurlacoste** [comment]
Yes, we just need to wait a little bit.

**Comment by endyjasmi** [comment]
Hello, I encountered the same problem.
When I try to `composer require` it returns:
```


  [Composer\Repository\RepositorySecurityException]
  The contents of https://packagist.org/p/provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json do not match its signature. This could indicate a man-in-the-middle attack. Try running composer again
   and report this if you think it is a mistake.


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

Tried adding `"repositories": { "packagist": { "url": "https://packagist.org", "type": "composer" } }` to `composer config -ge`. didn't work.

Here's my `php -v`
```
PHP 7.1.12 (cli) (built: Nov 23 2017 04:20:40) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

**Comment by dragdown** [comment]
For Mac User:
sudo killall -HUP mDNSResponder
 nslookup packagist.org
Name:	packagist.org
Address: 144.217.203.53
Worked for me

**Comment by notflip** [comment]
I think it has to do with Packagist being down the past hour. I'm also getting errors. I sent them on Twitter, I'll update this thread when I hear more.

**Comment by Keirul** [comment]
@endyjasmi Packagist DNS is down. Scroll up.

**Comment by notflip** [comment]
I guess on a shared hosting I'll have to contact the sysadmins to perform the DNS flush?

**Comment by akentner** [comment]
that my problem, too

**Comment by shonjord** [comment]
Have the same problem as well

**Comment by RonnyGitHub** [comment]
Indeed, what helped us was using a different DNS:

https://developers.google.com/speed/public-dns/

**Comment by LS05** [comment]
Tried now locally and it's working!

**Comment by hirnschmalz** [comment]
Flushing DNS cache (or using Google DNS servers temporary) works for me.

**Comment by Keirul** [comment]
Solved here as well, I'm on Linux so I switched to Google DNS -> https://developers.google.com/speed/public-dns/

**Comment by Okipa** [comment]
For macOs users, flush your DNS : `dscacheutil -flushcache;sudo killall -HUP mDNSResponder;`

**Comment by snightingale** [comment]
Odd, flushing the DNS still hasnt worked.  Still getting

```
[Composer\Repository\RepositorySecurityException]                                                                                                                                                                                                                                     
  The contents of https://packagist.org/p/provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json do not match its signature. This could indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.
```

Im on Linux and used `service dnsmasq restart` (as we dont have `nscd`)

Maybe adding a Google dns..

**Comment by kiaplayer** [comment]
Same here. Google DNS didn't help (Ubuntu 16.04 in VirtualBox for Windows 10).

**Comment by Keirul** [comment]
@snightingale @kiaplayer
Switching to Google DNS solves it. And using the following to clear any leftover dns: 

> systemctl restart systemd-resolved.service

**Comment by Rui-Git** [comment]
I'm on Mac

Flushing DNS doesn't work
Adding repositories in composer.json doesn't work

Changing DNS to google DNS Worked

**Comment by WDD-Marv** [comment]
already using google dns, so there's no resolution there.
running composer through the public proxy built into toranproxy does work, however.

**Comment by ikas** [comment]
Google DNS also solved for me (CentOS)

**Comment by notflip** [comment]
Does anyone know a solution for a **shared hosting**? Where I can't run scripts, change settings..

**Comment by smartdeath** [comment]
This is my composer.json test it 

> {
	"name": "smartdeath/mvc",
	"description": "Simple composer project",
	"type": "project",
	"license": "MIT",
	"authors": [
		{
			"name": "smartdeath",
			"email": "1smartdeath@gmail.com"
		}
	],
	"repositories": {
		"packagist": {
			"url": "https://packagist.org",
			"type": "composer"
		}
	},
	"require": {
		"php": ">=5.6.4",
		"nesbot/carbon": "^1.22"
	}
}

**Comment by vrkansagara** [comment]
```
"repositories": {
    "packagist": {
      "url": "https://packagist.org",
      "type": "composer"
    }
  }
```
not working.

**Comment by Keirul** [comment]
@notflip You could locally do a composer install and manually move the packages yourself. I don't see another solution for you.

**Comment by notflip** [comment]
@Keirul I'm affraid that will be it. Thank you!

**Comment by denisov1985** [comment]
Flushing DNS works for me.
Is there any way to avoid this in the future?

**Comment by Keirul** [comment]
@denisov1985 Not really. It would be the same thing as planning to use an alternative for when Google is down.

What you could do is create a private repository and host the packages you personally use for that project. So if you use those dependencies elsewhere you can retrieve them yourself. 

But update-wise you can't change a thing.

**Comment by Reserford1991** [comment]
Hello everyone. Does somebody know how to flush DNS on Ubuntu desktop 16.04?

**Comment by akadko** [comment]
@Reserford1991 Worked for me: `systemctl restart systemd-resolved.service`

**Comment by Keirul** [comment]
@Reserford1991 Indeed, @akadko was faster then me, I already posted that before :)

**Comment by Reserford1991** [comment]
@akadko, @Keirul Thanks guys, but composer require laravel/installer still does not work properly. Will try to download installer manually.

**Comment by ZenelB** [comment]
For everyone who is using Windows, just flush your DNS with `ipconfig /flushdns` in your CMD.

This worked for me

**Comment by Reserford1991** [comment]
Update composer require laravel/installer works already

**Comment by treuter** [comment]
```composer update``` is working again!

**Comment by WallTearer** [comment]
Our team was monitoring this issue for the past hour, and now it works again. Looks like something was misbehaving on the composer/packagist side. 
Interestingly, while the issue was happening, the request `GET https://packagist.org/p/provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json ` was returning 200 with an empty body, and now it returns 404 - maybe it has something to do with the issue that most of us had here.

**Comment by stof** [comment]
@WallTearer these `provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json` is a cache-busted URL (see the `240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973` part being a hash of the file ?). The files are dropped after some time when they got replaced (the cron is dumping files every few minutes, and the `latest` file probably changes at each dump).
Look in `packages.json` for the new hash of the `provider-latest` file.

**Comment by nguyentamgm** [comment]
Running `composer self-update` helped me to get rid of this error.

**Comment by Keirul** [comment]
@adette You commented on an old issue which was resolved since packagist.org had dns issues.
"This should indicate a man-in-the-middle attack."

This line of text implies it, I agree. But that wasn't the issue.
It clearly shows you haven't read the other comments, which is really unfortunate.
