### ISSUE TITLE
Composer fails to install private repository from Satis...

### ISSUE THREAD

**Issue by taylorotwell** [composer/composer#5229]
I have a Satis serving the laravel/spark private package (https://spark-satis.laravel.com)... 

However, it appears the package downloads fine but then Composer throws an error about writing to the cache... 

![screen shot 2016-04-21 at 10 27 52 am](https://cloud.githubusercontent.com/assets/463230/14714723/b78b451e-07ab-11e6-9fb2-63a9f89ee1c8.png)

**Comment by taylorotwell** [comment]
Composer version 1.0.2 2016-04-21 12:30:18

**Comment by alcohol** [comment]
Could you please provide the output while running in `-vvv`?

Also, the assumption that it has downloaded the package properly could be wrong (the "100%" can be misleading in some situations).

**Comment by taylorotwell** [comment]
```
  - Installing laravel/spark (v1.0.3)
Downloading https://api.github.com/repos/laravel/spark/zipball/a7feca211b7eb87c966e59b3b7a0bbda946a943e
    Downloading: 100%
Could not fetch https://codeload.github.com/laravel/spark/legacy.zip/a7feca211b7eb87c966e59b3b7a0bbda946a943e?access_token={redacted}, enter your github.com credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+defiant+2016-04-22+1441
to retrieve a token. It will be stored in "/Users/Taylor/.composer/auth.json" for future use by Composer.
Token (hidden):
Downloading https://api.github.com/
Token stored successfully.
    Downloading: 100%
/Users/Taylor/Documents/Code/Laravel/laravel/vendor/laravel/spark/270c131c4f4a847bc0ec5204136e6312 does not exist, can not write into cache

Failed: [ErrorException] 0: copy(/Users/Taylor/Documents/Code/Laravel/laravel/vendor/laravel/spark/270c131c4f4a847bc0ec5204136e6312): failed to open stream: No such file or directory


  [ErrorException]
  copy(/Users/Taylor/Documents/Code/Laravel/laravel/vendor/laravel/spark/270c131c4f4a847bc0ec5204136e6312): failed to open stream: No such file or directory


Exception trace:
 () at phar:///Users/Taylor/.bin/composer/src/Composer/Cache.php:128
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 copy() at phar:///Users/Taylor/.bin/composer/src/Composer/Cache.php:128
 Composer\Cache->copyFrom() at phar:///Users/Taylor/.bin/composer/src/Composer/Downloader/FileDownloader.php:153
 Composer\Downloader\FileDownloader->doDownload() at phar:///Users/Taylor/.bin/composer/src/Composer/Downloader/FileDownloader.php:91
 Composer\Downloader\FileDownloader->download() at phar:///Users/Taylor/.bin/composer/src/Composer/Downloader/ArchiveDownloader.php:36
 Composer\Downloader\ArchiveDownloader->download() at phar:///Users/Taylor/.bin/composer/src/Composer/Downloader/ZipDownloader.php:65
 Composer\Downloader\ZipDownloader->download() at phar:///Users/Taylor/.bin/composer/src/Composer/Downloader/DownloadManager.php:213
 Composer\Downloader\DownloadManager->download() at phar:///Users/Taylor/.bin/composer/src/Composer/Installer/LibraryInstaller.php:176
 Composer\Installer\LibraryInstaller->installCode() at phar:///Users/Taylor/.bin/composer/src/Composer/Installer/LibraryInstaller.php:90
 Composer\Installer\LibraryInstaller->install() at phar:///Users/Taylor/.bin/composer/src/Composer/Installer/InstallationManager.php:152
 Composer\Installer\InstallationManager->install() at phar:///Users/Taylor/.bin/composer/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar:///Users/Taylor/.bin/composer/src/Composer/Installer.php:572
 Composer\Installer->doInstall() at phar:///Users/Taylor/.bin/composer/src/Composer/Installer.php:228
 Composer\Installer->run() at phar:///Users/Taylor/.bin/composer/src/Composer/Command/UpdateCommand.php:173
 Composer\Command\UpdateCommand->execute() at phar:///Users/Taylor/.bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///Users/Taylor/.bin/composer/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///Users/Taylor/.bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///Users/Taylor/.bin/composer/src/Composer/Console/Application.php:189
 Composer\Console\Application->doRun() at phar:///Users/Taylor/.bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///Users/Taylor/.bin/composer/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar:///Users/Taylor/.bin/composer/bin/composer:43
 require() at /Users/Taylor/.bin/composer:24

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```

**Comment by taylorotwell** [comment]
I fixed this by entirely removing and re-installing Composer fresh.

**Comment by alcohol** [comment]
I do not quite understand why that would fix anything related to the caching directory. Nothing left to investigate or debug at this point though. I guess we'll just call it a fluke and blame cosmic radiation :-)

**Comment by jtanmay-dev** [comment]
I am facing the same issue! even reinstalling composer does not fix it!
