### ISSUE TITLE
Composer environment variables missing when composer installed locally

### ISSUE THREAD

**Issue by hackel** [composer/composer#8298]
When I install a specific version of composer locally in my project and run `vendor/bin/composer install`, composer-specific environment variables are not available to my scripts.  If I run a standalone composer install, they work fine.

Specifically, the following environment variables only appear when I run a standalone composer install:
```sh
COMPOSER_BINARY='/usr/local/bin/composer'
COMPOSER_DEV_MODE='1'
GIT_ASKPASS='echo'
PHP_BINARY='/usr/bin/php7.2'
```

I'm not sure if the issue lies with composer itself or symfony/process.

Edit: I suspect this is related to https://github.com/symfony/symfony/issues/26451, but I'm not sure why running the phar vs the locally installed version would make a difference with env vars being stored in $_SERVER.

My `composer.json`:

```json
{
    "require": {
        "composer/composer": "^1.9"
    },
    "scripts": {
        "post-install-cmd": [
            "set",
            "if [ \"$COMPOSER_DEV_MODE\" = 1 ]; then echo yes; else echo no; fi"
        ]
    }
}
```

Output of `/usr/local/bin/composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.2.19
PHP binary path: /usr/bin/php7.2
```

Output of `vendor/bin/composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Composer version: 1.9.0
PHP version: 7.2.19
PHP binary path: /usr/bin/php7.2
```

**Comment by Seldaek** [comment]
I don't really see the difference either, except for the dependency versions as you noted. I can't really say we want to support source usage though, if you can figure out the problem and send a PR that's great but otherwise if you don't use the phar you're kinda on your own.

**Comment by hackel** [comment]
@alcohol This is not a "support" issue, it is a bug that really needs to be resolved.  Please correct the label.

Update: If `COMPOSER_DEV_MODE` is initialized to *any* value prior to running composer, `putenv` will correctly change it to 0/1 and everything works as expected.

**Comment by Seldaek** [comment]
@hackel I could not reproduce this but maybe the commit I just pushed fixes it. Please give it a shot with a `composer self-update --snapshot`

**Comment by hackel** [comment]
@Seldaek Sorry, I just saw this.  I tested again with composer 1.10.6, symfony/process 4.4.7, and PHP 7.4.5 and unfortunately the issue remains.

I was able to dig a little deeper.  composer.phar is built with symfony/process v2.8.52, and if I install that version into a local project, this issue disappears.  It only seems to happen with symfony/process >=3.4.3, and was introduced with this commit: https://github.com/symfony/process/commit/977afa0c3658bdef76eb965476260042752d1759?w=1.  Reverting that and using `getenv` does indeed fix it.

**Comment by Seldaek** [comment]
Ok, the problem was the is_string() at https://github.com/symfony/process/commit/977afa0c3658bdef76eb965476260042752d1759?w=1#diff-9a01fc0e340da4c3f1e4a16029a63977R1724 - I set the value to an int, but that's not valid so it didn't propagate.

Last commit properly fixes it, I managed to reproduce the issue before I applied the fix.
