### ISSUE TITLE
Composer not update new version from packagist

### ISSUE THREAD

**Issue by si6-nl** [composer/composer#8347]
My `composer.json`:

```json
"si6/base-rest-framework": "2.3.*"
```

Output of `composer diagnose`:

```
The version field is present, it is recommended to leave it out if the package is published on Packagist.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.3.8
PHP binary path: /usr/local/Cellar/php/7.3.8/bin/php
```

When I run this command:

```
composer update --prefer-source si6/base-rest-framework

```

I get the following output:

```
Nothing to install or update
```

And I expected this to happen:

I released new version 2.4

https://github.com/si6-nl/base-rest-framework/releases/tag/2.3.4

But compose not update package to 2.4

```
composer info si6/base-rest-framework                  
name     : si6/base-rest-framework
descrip. : SI6 package base.
keywords : 
versions : * 2.3.3
```

**Comment by alcohol** [comment]
I'm confused. You show that you are requiring `2.3.*`. You say you released `2.4`. then you add a link to `2.3.4`. And then you say you expect an update to `2.4` (which does not match `2.3.*` obviously). Can you please be more specific about what exactly is wrong here and what you expect to happen?

**Comment by tintnaingwinn** [comment]
I'm also can't update new version from my package.

<img width="721" alt="Screen Shot 2019-09-30 at 9 36 03 PM" src="https://user-images.githubusercontent.com/13062143/65909083-ceee7880-e3ed-11e9-91f6-1de37596905a.png">

I had updated it until 3.0.4. But I got only version 3.0.2.

From https://packagist.org/packages/tintnaingwin/kuu-pyaung
<img width="1179" alt="Screen Shot 2019-10-01 at 1 48 07 AM" src="https://user-images.githubusercontent.com/13062143/65909168-02c99e00-e3ee-11e9-99e3-58c0a7ad4eba.png">

**Comment by merk** [comment]
I am seeing the same thing. I am unable to install v1.2.3 of `loyaltycorp/requesthandlers` on my local machine - v1.2.2 is the last version shown in `composer show --all loyaltycorp/requesthandlers` output.

My colleagues' machines all show v1.2.3 existing. I have tried removing my .composer cache directory, reinstalling composer, using a freshly installed composer.phar in a local directory and all of them result in stale output.

**Comment by merk** [comment]
Using a VPN to appear from the USA the problem goes away.

It appears that the Singapore mirror at a minimum is broken (along with most of the 3rd party mirrors who must be mirroring singapore).

**Comment by karunais13** [comment]
I'm also can't update new version from my package. Even with previous version of composer. Not able to grab any latest package that release into packagist.org. 

![image](https://user-images.githubusercontent.com/18754736/65956373-d14be380-e47c-11e9-8e99-84f82f8f5915.png)

**Comment by alcohol** [comment]
I can't do anything with a screenshot. Also if you are submitting output logs, make sure you run commands in very verbose mode (`-vvv`) otherwise it is virtually useless information only.

**Comment by karunais13** [comment]
This is the output when I run **composer require karu/simple-js-localization -vvv**
```shell

Reading ./composer.json
Loading config file C:/Users/ed209/AppData/Roaming/Composer/config.json
Loading config file C:/Users/ed209/AppData/Roaming/Composer/auth.json
Loading config file ./composer.json
Checked CA file C:\Users\ed209\AppData\Local\Temp\ope424D.tmp: valid
Executing command (C:\Users\ed209\Projects\Nippon\mycrm-v2): git branch --no-color --no-abbrev -v
Reading C:/Users/ed209/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/ed209/AppData/Roaming/Composer/config.json
Loading config file C:/Users/ed209/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/ed209/AppData/Roaming/Composer/composer.json
Loading config file C:\Users\ed209\AppData\Roaming\Composer/auth.json
Reading C:\Users\ed209\AppData\Roaming\Composer/auth.json
Reading C:\Users\ed209\Projects\Nippon\mycrm-v2/vendor/composer/installed.json
Reading C:/Users/ed209/AppData/Roaming/Composer/vendor/composer/installed.json
Running 1.9.0 (2019-08-02 20:55:32) with PHP 7.2.9 on Windows NT / 10.0
Downloading https://repo.packagist.org/packages.json
Writing C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/packages.json into cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2013.json from cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2014.json from cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2015.json from cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2016.json from cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2017.json from cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2018.json from cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2018-10.json from cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2019-01.json from cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2019-04.json from cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-2019-07.json from cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-archived.json from cache
Reading C:/Users/ed209/AppData/Local/Composer/repo/https---repo.packagist.org/p-provider-latest.json from cache
Downloading https://packagist.org/search.json?q=karu/simple-js-localization&type=


  [InvalidArgumentException]
  Could not find a version of package karu/simple-js-localization matching your minimum-stability (dev). Require it with an explicit version constraint allowing its desired stability.


Exception trace:
 () at phar://C:/laragon/bin/composer/composer.phar/src/Composer/Command/InitCommand.php:757
 Composer\Command\InitCommand->findBestVersionAndNameForPackage() at phar://C:/laragon/bin/composer/composer.phar/src/Composer/Command/InitCommand.php:413
 Composer\Command\InitCommand->determineRequirements() at phar://C:/laragon/bin/composer/composer.phar/src/Composer/Command/RequireCommand.php:140
 Composer\Command\RequireCommand->execute() at phar://C:/laragon/bin/composer/composer.phar/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar://C:/laragon/bin/composer/composer.phar/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/laragon/bin/composer/composer.phar/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar://C:/laragon/bin/composer/composer.phar/src/Composer/Console/Application.php:267
 Composer\Console\Application->doRun() at phar://C:/laragon/bin/composer/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/laragon/bin/composer/composer.phar/src/Composer/Console/Application.php:106
 Composer\Console\Application->run() at phar://C:/laragon/bin/composer/composer.phar/bin/composer:61
 require() at C:\laragon\bin\composer\composer.phar:24

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

````

**Comment by alcohol** [comment]
Could be that one of the mirrors is out of sync perhaps? @Seldaek is there any way to check this?

**Comment by Seldaek** [comment]
Hey, thanks for reporting this, and sorry for not reacting faster, had a few busy days with everyone sick at home..

There was an issue with the Singapore mirror for the packagist metadata which I now resolved so it's busy catching up now and should be back on track soon. Sorry for the trouble!

**Comment by arcanedev-maroc** [comment]
Hi @Seldaek,

I think i have the same issue. I can't pull the lastest version of a package.

I forced the latest version of the package as min version and this is what i got when i (re)try to update about 40 minutes now:

```
 Problem 1
    - The requested package arcanesoft/auth ~3.1.4 exists as arcanesoft/auth[0.0.1, 0.0.2, 0.1.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 1.0.0, 1.0.1, 1.1.0, 1.10.0, 1.11.0, 1.12.0, 1.12.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.3.0, 2.3.1, 3.0.0, 3.0.1, 3.1.0, 3.1.1, 3.1.2, 3.1.3, dev-develop, dev-laravel-5.3, dev-laravel-5.4, dev-laravel-5.5, dev-master, dev-path-validation, dev-v0.x_laravel51] but these are rejected by your constraint.
  Problem 2
    - arcanesoft/backups 1.1.0 requires arcanesoft/auth ~3.0 -> satisfiable by arcanesoft/auth[3.0.0, 3.0.1, 3.1.0, 3.1.1, 3.1.2, 3.1.3] but these conflict with your requirements or minimum-stability.
    - arcanesoft/backups 1.1.0 requires arcanesoft/auth ~3.0 -> satisfiable by arcanesoft/auth[3.0.0, 3.0.1, 3.1.0, 3.1.1, 3.1.2, 3.1.3] but these conflict with your requirements or minimum-stability.
    - Installation request for arcanesoft/backups ~1.1.0 -> satisfiable by arcanesoft/backups[1.1.0].
```

https://packagist.org/packages/arcanesoft/auth#3.1.4

Any idea how to solve this? Thanks

**Comment by Seldaek** [comment]
@arcanedev-maroc we had some metadata dumping issues which should be resolved now, maybe try again?

**Comment by arcanedev-maroc** [comment]
Yep, the issue was solved. 

Thanks a lot @Seldaek :+1:

**Comment by rocket-power** [comment]
@Seldaek I believe this maybe an open issue still. I am not able to update to the latest package versions that I have submitted from Singapore. If I use a VPN to the US and UK then I can update without problem. Singapore mirror still having issues?

**Comment by Seldaek** [comment]
@rocket-power This has been resolved, we had an issue with the metadata mirroring over the weekend sorry about that. If you still see issues with the Singapore mirror let me know.

**Comment by feryardiant** [comment]
Come across the same issue with my [package](https://packagist.org/packages/feryardiant/wpdev), it keep showing `v0.2.5` while I just released [`v0.2.7`](https://github.com/feryardiant/wpdev/releases) a few moment ago.

**Comment by Seldaek** [comment]
from the update log:

Reading composer.json of feryardiant/wpdev (v0.2.8)
Skipped tag v0.2.8, tag (0.2.8.0) does not match version (0.2.5.0) in composer.json
Reading composer.json of feryardiant/wpdev (v0.2.7)
Skipped tag v0.2.7, tag (0.2.7.0) does not match version (0.2.5.0) in composer.json
Reading composer.json of feryardiant/wpdev (v0.2.6)
Skipped tag v0.2.6, tag (0.2.6.0) does not match version (0.2.5.0) in composer.json

You should rather remove `version` from composer.json

**Comment by feryardiant** [comment]
Ah, my bad 😅

Thank you @Seldaek

**Comment by lloricode** [comment]
same issue as mine, 

this is my package https://packagist.org/packages/lloricode/laravel-paymaya-sdk

im trying to get `v0.3.1`, give an error 
```json
        "lloricode/laravel-paymaya-sdk": "^0.3.1",
```

result
```
Loading composer repositories with package information                                                                                                                  Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires lloricode/laravel-paymaya-sdk ^0.3.1, found lloricode/laravel-paymaya-sdk[dev-master, v0.1.0, ..., v0.3.0] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

even trying both 
```json
        "lloricode/laravel-paymaya-sdk": "*",
```
```json
        "lloricode/laravel-paymaya-sdk": "dev-master",
```
cannot get the latest code

**Comment by divineniiquaye** [comment]
@lloricode Experiencing same issue, I guess it's a problem with their servers.

**Comment by lloricode** [comment]
> @lloricode Experiencing same issue, I guess it's a problem with their servers.

thanks for response, 

do you have a temporary solution? else ill just copy this to bitbucket as private repo

**Comment by Seldaek** [comment]
@lloricode which IP does repo.packagist.org  resolve to for you? And also are you using a custom repo? Please post a full output of `composer update -vvv` here, or preferrably in a new issue so we don't spam everyone here.

**Comment by lloricode** [comment]
> @lloricode which IP does repo.packagist.org resolve to for you? And also are you using a custom repo? Please post a full output of `composer update -vvv` here, or preferrably in a new issue so we don't spam everyone here.

Hi @Seldaek 

Thank for response,

It already work the day after I'm reporting here
I will create new issue if this occur again

thank you
