### ISSUE TITLE
Composer 2.0.3 fails bitbucket api authentication

### ISSUE THREAD

**Issue by markhowells** [composer/composer#9369]
My bitbucket auth is failing for v2.0.3 for a bitbucket repo

Using 1.10.16 it works fine

Here's my config.json repositories fragment

````
    "repositories": [
        {
            "type": "vcs",
            "url": "https://bitbucket.org/*****/*********"
        }
    ],
````
And here's what I see when I execute an update

**Show version, add auth key, and perform, update (output truncated)**

````
C:\Users\Mark\PhpstormProjects\dgpservices>composer --version
Composer version 1.10.16 2020-10-24 09:55:59

C:\Users\Mark\PhpstormProjects\dgpservices>composer config bitbucket-oauth.bitbucket.org <<my-consumer-key>>
<< my-consumer-secret>>

C:\Users\Mark\PhpstormProjects\dgpservices>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
<snip>
````

**Now update to version 2**

````
C:\Users\Mark\PhpstormProjects\dgpservices>composer self-update --2
Updating to version 2.0.3 (2.x channel).
   Downloading (100%)
Use composer self-update --rollback to return to version 1.10.16
````

**Now perform update again and I'm prompted for username and password**

````
C:\Users\Mark\PhpstormProjects\dgpservices>composer update
Loading composer repositories with package information
Updating dependencies
    Authentication required (api.bitbucket.org):
      Username: ^CTerminate batch job (Y/N)?
````

**Rolling back fixes it again.**

````
C:\Users\Mark\PhpstormProjects\dgpservices>composer self-update --rollback
Rolling back to version 2020-10-24_09-55-59-1.10.16.

C:\Users\Mark\PhpstormProjects\dgpservices>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
````

performing the config command using v2.0.3 makes no difference either.

I expected it to work in both cases.

**Comment by aprokopenko** [comment]
Hi,

BitBucket Auth is not working in 1.* too.

I create auth.json with correct credentials (actually we have CI and nothing changed in CI configs) and for any BitBucket private repo it just says "Failed to download {package} from dist: Could not authenticate against bitbucket.org"

**Comment by Seldaek** [comment]
Should now be fixed.. you can try with `composer self-update --snapshot` until the next release. It now requires OAuth setup as per https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/ - but then uses it correctly for API requests as well as downloading zip files.

**Comment by Seldaek** [comment]
2.0.4 is out now with this fix.

**Comment by juliangut** [comment]
I'm still experiencing this issue with 2.0.4 freshly installed

**Comment by Seldaek** [comment]
That's not helping me help you.. I can't reproduce at this point as I fixed the only issue I've found.

If you still have a problem, give more details or you're gonna have to debug it yourself..

Full composer update -vvv output would be a good start, output of composer diagnose too. 

The original issue author is on windows, is everyone experiencing this on windows?

**Comment by juliangut** [comment]
I didn't see original poster was on Windows, and I assumed the fix didn't actually work for some reason

linux, 5.6.13 kernel
php 7.3.18
git 2.21.3

Bitbucket OAuth consumer is correctly configured (it was working up until update to composer2), and I already have a _/home/xxxx/.config/composer/auth.json_ file as follows

```json
{
    "github-oauth": {
        "github.com": "xxxx"
    },
    "bitbucket-oauth": {
        "bitbucket.org": {
            "consumer-key": "xxxx",
            "consumer-secret": "xxxx"
        }
    }
}
```

Anyway it fails authenticating, prompts for consumer key/secret _twice_ and finally exits with the exception

```
$> composer update -vvv
Reading ./composer.json
Loading config file /home/xxxx/.config/composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: valid
Executing command (/home/xxxx/xxxx/xxxx): git branch -a --no-color --no-abbrev -v
Reading /home/xxxx/.config/composer/composer.json
Loading config file /home/xxxx/.config/composer/auth.json
Loading config file /home/xxxx/.config/composer/composer.json
Loading config file /home/xxxx/.config/composer/auth.json
Reading /home/xxxx/.config/composer/auth.json
Reading /home/xxxx/xxxx/xxxx/vendor/composer/installed.json
Reading /home/xxxx/.config/composer/vendor/composer/installed.json
Loading plugin PHPStan\ExtensionInstaller\Plugin
The "ocramius/package-versions" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Loading plugin Infection\ExtensionInstaller\Plugin
Running 2.0.4 (2020-10-30 22:39:11) with PHP 7.3.18 on Linux / 5.6.13-100.fc30.x86_64
Reading ./composer.lock
Loading composer repositories with package information
Updating dependencies
Using HTTP basic authentication with username "yyyy"
Downloading https://api.bitbucket.org/2.0/repositories/xxxx/xxxx?fields=-project%2C-owner
[401] https://api.bitbucket.org/2.0/repositories/xxxx/xxxx?fields=-project%2C-owner
Using HTTP basic authentication with username "yyyy"
Downloading https://bitbucket.org/site/oauth2/access_token
[400] https://bitbucket.org/site/oauth2/access_token
Invalid OAuth consumer provided.
This can have two reasons:
1. You are authenticating with a bitbucket username/password combination
2. You are using an OAuth consumer, but didn't configure a (dummy) callback url
Executing command (CWD): git config bitbucket.accesstoken

Could not fetch https://api.bitbucket.org/2.0/repositories/xxxx/xxxx?fields=-project%2C-owner, please create a bitbucket OAuth token to access private repos
Follow the instructions on https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/
to create a consumer. It will be stored in "/home/xxxx/.config/composer/auth.json" for future use by Composer.
Ensure you enter a "Callback URL" (http://example.com is fine) or it will not be possible to create an Access Token (this callback url will not be used by composer)
Consumer Key (hidden): 
Consumer Secret (hidden): 
Using HTTP basic authentication with username "yyyy"
Downloading https://bitbucket.org/site/oauth2/access_token
[400] https://bitbucket.org/site/oauth2/access_token
Invalid OAuth consumer provided.
This can have two reasons:
1. You are authenticating with a bitbucket username/password combination
2. You are using an OAuth consumer, but didn't configure a (dummy) callback url
Downloading https://api.bitbucket.org/2.0/repositories/xxxx/xxxx?fields=-project%2C-owner
[401] https://api.bitbucket.org/2.0/repositories/xxxx/xxxx?fields=-project%2C-owner
Using HTTP basic authentication with username "yyyy"
Downloading https://bitbucket.org/site/oauth2/access_token
[400] https://bitbucket.org/site/oauth2/access_token
Invalid OAuth consumer provided.
This can have two reasons:
1. You are authenticating with a bitbucket username/password combination
2. You are using an OAuth consumer, but didn't configure a (dummy) callback url
Executing command (CWD): git config bitbucket.accesstoken

Could not fetch https://api.bitbucket.org/2.0/repositories/xxxx/xxxx?fields=-project%2C-owner, please create a bitbucket OAuth token to access private repos
Follow the instructions on https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/
to create a consumer. It will be stored in "/home/xxxx/.config/composer/auth.json" for future use by Composer.
Ensure you enter a "Callback URL" (http://example.com is fine) or it will not be possible to create an Access Token (this callback url will not be used by composer)
Consumer Key (hidden): 
Consumer Secret (hidden): 
Using HTTP basic authentication with username "yyyy"
Downloading https://bitbucket.org/site/oauth2/access_token
[400] https://bitbucket.org/site/oauth2/access_token
Invalid OAuth consumer provided.
This can have two reasons:
1. You are authenticating with a bitbucket username/password combination
2. You are using an OAuth consumer, but didn't configure a (dummy) callback url


  [Composer\Downloader\TransportException]      
  Could not authenticate against bitbucket.org  


Exception trace:
 () at phar:///usr/bin/composer/src/Composer/Util/AuthHelper.php:151
 Composer\Util\AuthHelper->promptAuthIfNeeded() at phar:///usr/bin/composer/src/Composer/Util/Http/CurlDownloader.php:448
 Composer\Util\Http\CurlDownloader->isAuthenticatedRetryNeeded() at phar:///usr/bin/composer/src/Composer/Util/Http/CurlDownloader.php:334
 Composer\Util\Http\CurlDownloader->tick() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:322
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:290
 Composer\Util\HttpDownloader->wait() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:81
 Composer\Util\HttpDownloader->get() at phar:///usr/bin/composer/src/Composer/Repository/Vcs/VcsDriver.php:166
 Composer\Repository\Vcs\VcsDriver->getContents() at phar:///usr/bin/composer/src/Composer/Repository/Vcs/BitbucketDriver.php:370
 Composer\Repository\Vcs\BitbucketDriver->fetchWithOAuthCredentials() at phar:///usr/bin/composer/src/Composer/Repository/Vcs/BitbucketDriver.php:94
 Composer\Repository\Vcs\BitbucketDriver->getRepoData() at phar:///usr/bin/composer/src/Composer/Repository/Vcs/HgBitbucketDriver.php:33
 Composer\Repository\Vcs\HgBitbucketDriver->getRootIdentifier() at phar:///usr/bin/composer/src/Composer/Repository/VcsRepository.php:179
 Composer\Repository\VcsRepository->initialize() at phar:///usr/bin/composer/src/Composer/Repository/ArrayRepository.php:266
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/bin/composer/src/Composer/Repository/ArrayRepository.php:55
 Composer\Repository\ArrayRepository->loadPackages() at phar:///usr/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:319
 Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading() at phar:///usr/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:185
 Composer\DependencyResolver\PoolBuilder->buildPool() at phar:///usr/bin/composer/src/Composer/Repository/RepositorySet.php:233
 Composer\Repository\RepositorySet->createPool() at phar:///usr/bin/composer/src/Composer/Installer.php:412
 Composer\Installer->doUpdate() at phar:///usr/bin/composer/src/Composer/Installer.php:251
 Composer\Installer->run() at phar:///usr/bin/composer/src/Composer/Command/UpdateCommand.php:230
 Composer\Command\UpdateCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:310
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:122
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:63
 require() at /usr/bin/composer:24

update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

```

```
$> composer diagnose
The "ocramius/package-versions" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.4
PHP version: 7.3.18
PHP binary path: /usr/bin/php
OpenSSL version: OpenSSL 1.1.1g FIPS  21 Apr 2020
cURL version: 7.65.3 libz 1.2.11 ssl OpenSSL/1.1.1g-fips
zip extension: not loaded
```

Am I the only one experiencing this?

**Comment by Seldaek** [comment]
@juliangut I certainly can not repro it.. Can you share a `composer update -vvv` using composer 1 (which works you say?).

Also here what is in username `yyyy` is it your consumer-key from bitbucket?

```

Using HTTP basic authentication with username "yyyy"
Downloading https://api.bitbucket.org/2.0/repositories/xxxx/xxxx?fields=-project%2C-owner
[401] https://api.bitbucket.org/2.0/repositories/xxxx/xxxx?fields=-project%2C-owner
```

**Comment by lloricode** [comment]
Hi, we did not use OAuth on Bitbucket, we just use ssh key in any private store in bitbucket, and we produce this

```
vagrant@homestead:~/code/laravel/test-project$ composer --version
Composer version 2.0.4 2020-10-30 22:39:11
vagrant@homestead:~/code/laravel/test-project$ composer u -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/vagrant/code/laravel/test-project): git branch -a --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/vagrant/.config/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/vagrant/code/laravel/test-project/vendor/composer/installed.json
Running 2.0.4 (2020-10-30 22:39:11) with PHP 7.4.12 on Linux / 5.4.0-52-generic
Reading ./composer.lock
Loading composer repositories with package information
Updating dependencies
Downloading https://api.bitbucket.org/2.0/repositories/halcyonlaravel/backup?fields=-project%2C-owner
[403] https://api.bitbucket.org/2.0/repositories/halcyonlaravel/backup?fields=-project%2C-owner
Executing command (CWD): git config bitbucket.accesstoken

Could not fetch https://api.bitbucket.org/2.0/repositories/halcyonlaravel/backup?fields=-project%2C-owner, please create a bitbucket OAuth token to access private repos
Follow the instructions on https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/
to create a consumer. It will be stored in "/home/vagrant/.config/composer/auth.json" for future use by Composer.
Ensure you enter a "Callback URL" (http://example.com is fine) or it will not be possible to create an Access Token (this callback url will not be used by composer)
Consumer Key (hidden):

```

**Comment by markhowells** [comment]
Hi,

Sorry to be slow testing this - I've been away.

Initially 2.0.4 failed, but debugging revealed that it was improperly trying to access the repo as a Mercurial repo.

I had to adjust my composer.json repositories url from 

    "url": "https://bitbucket.org/mjogltd/ancillary-utils"

to

    "url": "https://bitbucket.org/mjogltd/ancillary-utils.git"

The `.git` extension seemed to be assumed by composer v1.

So, it works for me now. TY

**Comment by Seldaek** [comment]
@markhowells that is odd, https://github.com/composer/composer/blob/1.10/src/Composer/Repository/Vcs/GitBitbucketDriver.php#L56 has always been requiring the .git for git bitbucket repos as it's the only way we have to distinguish them from mercurial ones.

@lloricode so for you the tweaks I did in 2.0.4 broke it? Please report as a new issue with a complete output from `composer update -vvv` on both 2.0.3 and 2.0.4 so I can see what's going on exactly when it needs to take the ssh key auth path.

**Comment by lloricode** [comment]
> @markhowells that is odd, https://github.com/composer/composer/blob/1.10/src/Composer/Repository/Vcs/GitBitbucketDriver.php#L56 has always been requiring the .git for git bitbucket repos as it's the only way we have to distinguish them from mercurial ones.
> 
> @lloricode so for you the tweaks I did in 2.0.4 broke it? Please report as a new issue with a complete output from `composer update -vvv` on both 2.0.3 and 2.0.4 so I can see what's going on exactly when it needs to take the ssh key auth path.

@Seldaek ok will submit new issue sooner

**Comment by Seldaek** [comment]
Closing here as I have no idea what to do anymore, if there is still an issue with latest Composer please reopen with repro details.
